(function(){
  var blank=function(en,palette){return{name:"Name",english:en,quote:"한마디를 입력해 주세요.",gender:"Gender",age:"Age",job:"Job",animal:"Animal",body:"Body",tags:"TAG 01, TAG 02, TAG 03",image:"",palette:palette,appearanceTitle:"외관",appearance:"외관을 자유롭게 기록해 주세요.",traitTitle:"핵심 특징",traits:"캐릭터의 특징을 자유롭게 기록해 주세요."};};
  var initial={pairName:"PAIR NAME",catchphrase:"PAIR CONTENTS",pairText:"두 사람의 관계를 자유롭게 기록해 주세요.",pairImage:"",left:blank("CHARACTER A",["#7768b5","#aaa0d5","#d7d1ec","#f0edf8"]),right:blank("CHARACTER B",["#b3975d","#d0bd8d","#e7dcc0","#f6f1e5"]),header:"#282520",paper:"#ffffff",visible:{palette:true,quote:true,tags:true,profile:true,appearance:true,traits:true,pair:true}};
  var stored=localStorage.getItem("welog-pair-sheet-v2"),state=stored?JSON.parse(stored):initial,tab="header";
  var tabs=[["header","H","헤더"],["left","A","캐릭터 A"],["right","B","캐릭터 B"],["pair","♡","페어"],["image","I","이미지"],["color","C","컬러"],["omit","✓","생략"]];
  var q=function(s){return document.querySelector(s)},esc=function(v){return String(v||"").replace(/[&<>\"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c]})},lines=function(v){return String(v||"").split("\n").filter(Boolean)};
  function persist(){localStorage.setItem("welog-pair-sheet-v2",JSON.stringify(state));}
  function get(path){return path.split(".").reduce(function(o,k){return o[k]},state)}
  function set(path,value){var p=path.split("."),o=state;p.slice(0,-1).forEach(function(k){o=o[k]});o[p[p.length-1]]=value;persist();renderSheet();}
  function input(label,path,area){return '<label class="control"><span>'+label+'</span>'+(area?'<textarea data-path="'+path+'">'+esc(get(path))+'</textarea>':'<input data-path="'+path+'" value="'+esc(get(path))+'">')+'</label>';}
  function color(label,path){return'<label class="color"><span>'+label+'</span><input type="color" data-path="'+path+'" value="'+get(path)+'"></label>'}
  function paletteControls(side){return'<h3>컬러 팔레트</h3><div class="palette-controls">'+state[side].palette.map(function(v,i){return'<input aria-label="팔레트 '+(i+1)+'" type="color" data-path="'+side+'.palette.'+i+'" value="'+v+'">'}).join("")+'</div>';}
  function renderTabs(){q("#tabs").innerHTML=tabs.map(function(t){return'<button data-tab="'+t[0]+'" class="'+(tab===t[0]?"on":"")+'"><b>'+t[1]+'</b><small>'+t[2]+'</small></button>'}).join("");q("#tabs").onclick=function(e){var b=e.target.closest("button");if(b){tab=b.dataset.tab;renderTabs();renderControls();}}}
  function renderControls(){var h="",side;
    if(tab==="header")h='<p class="section-label">HEADER</p><h2>헤더</h2>'+input("페어명","pairName")+input("캐치프레이즈","catchphrase");
    if(tab==="left"||tab==="right"){side=tab;h='<p class="section-label">CHARACTER '+(side==="left"?"A":"B")+'</p><h2>'+esc(state[side].name)+'</h2>'+input("이름",side+".name")+input("영문 표기",side+".english")+input("한마디",side+".quote",true)+paletteControls(side)+'<div class="two">'+input("젠더",side+".gender")+input("나이",side+".age")+input("직업",side+".job")+input("동물화",side+".animal")+input("체형",side+".body")+'</div>'+input("태그 (쉼표로 구분)",side+".tags")+input("외관 제목",side+".appearanceTitle")+input("외관 서술",side+".appearance",true)+input("특징 제목",side+".traitTitle")+input("핵심 특징",side+".traits",true);}
    if(tab==="pair")h='<p class="section-label">PAIR</p><h2>페어 특징</h2>'+input("관계 서술","pairText",true);
    if(tab==="image")h='<p class="section-label">IMAGE</p><h2>이미지</h2><p class="hint">시트 안의 이미지 칸을 클릭해 이미지를 넣으세요. 캐릭터별 메인 이미지 한 장과 합본 이미지 한 장을 사용할 수 있습니다.</p><button class="remove" data-remove="pairImage">합본 이미지 삭제</button><button class="remove" data-remove="left">A 메인 이미지 삭제</button><button class="remove" data-remove="right">B 메인 이미지 삭제</button>';
    if(tab==="color")h='<p class="section-label">COLOR</p><h2>전체 컬러</h2>'+color("헤더","header")+color("시트 배경","paper")+'<p class="hint">캐릭터 컬러는 A/B 메뉴의 4색 팔레트에서 조정할 수 있습니다.</p>';
    if(tab==="omit"){var opts=[["palette","컬러 팔레트"],["quote","한마디"],["tags","태그"],["profile","기본 프로필"],["appearance","외관 서술"],["traits","핵심 특징"],["pair","페어 특징"]];h='<p class="section-label">SHOW / HIDE</p><h2>표시할 항목</h2><p class="hint">체크를 해제한 항목은 결과에서도 생략됩니다.</p>'+opts.map(function(x){return'<label class="check"><input type="checkbox" data-visible="'+x[0]+'" '+(state.visible[x[0]]?"checked":"")+'><span>'+x[1]+'</span></label>'}).join("")+'<button class="reset" id="resetBtn">전체 초기화</button>';}
    q("#controls").innerHTML=h;q("#controls").oninput=function(e){if(e.target.dataset.path)set(e.target.dataset.path,e.target.value);if(e.target.dataset.visible){state.visible[e.target.dataset.visible]=e.target.checked;persist();renderSheet();}};q("#controls").onclick=function(e){var r=e.target.dataset.remove;if(r){if(r==="pairImage")state.pairImage="";else state[r].image="";persist();renderSheet();}if(e.target.id==="resetBtn"&&confirm("전체 내용을 초기화할까요?")){state=JSON.parse(JSON.stringify(initial));persist();renderControls();renderSheet();}};
  }
  function img(path,label,cls){var v=get(path);return'<label class="img '+cls+'" data-image="'+path+'">'+(v?'<img src="'+v+'" alt="">':'<span>＋<small>'+label+'</small></span>')+'<input type="file" accept="image/*"></label>'}
  function textBlock(no,title,bold,body){return'<div class="text-block"><h3><b>'+no+'</b>'+title+'</h3><strong>'+esc(bold)+'</strong>'+lines(body).map(function(x){return'<p>'+esc(x)+'</p>'}).join("")+'</div>'}
  function profile(side){var p=state[side],v=state.visible,h='<article class="profile '+side+'"><div class="profile-title"><b>'+esc(p.name)+'</b><span>'+esc(p.english)+'</span></div>'+img(side+".image","메인 이미지","main-image");if(v.palette)h+='<div class="palette-bar">'+p.palette.map(function(c){return'<i style="background:'+c+'"></i>'}).join("")+'</div>';if(v.quote)h+='<blockquote class="quote">“'+esc(p.quote)+'”</blockquote>';if(v.tags)h+='<div class="tags">'+p.tags.split(",").filter(Boolean).map(function(x){return'<span>'+esc(x.trim())+'</span>'}).join("")+'</div>';if(v.profile)h+='<div class="facts"><div><span>젠더</span><b>'+esc(p.gender)+'</b></div><div><span>나이</span><b>'+esc(p.age)+'</b></div><div><span>직업</span><b>'+esc(p.job)+'</b></div><div><span>동물화</span><b>'+esc(p.animal)+'</b></div><div><span>체형</span><b>'+esc(p.body)+'</b></div></div>';if(v.appearance)h+=textBlock("01","외관 서술",p.appearanceTitle,p.appearance);if(v.traits)h+=textBlock("02","핵심 특징",p.traitTitle,p.traits);return h+"</article>";}
  function renderSheet(){document.documentElement.style.setProperty("--a",state.left.palette[0]);document.documentElement.style.setProperty("--b",state.right.palette[0]);document.documentElement.style.setProperty("--head",state.header);document.documentElement.style.setProperty("--paper",state.paper);var h='<div class="sheet-head"><div><i>A</i><p><b>'+esc(state.left.name)+'</b><span>'+esc(state.left.english)+'</span></p></div><section><b>'+esc(state.pairName)+'</b><span>'+esc(state.catchphrase)+'</span></section><div class="right-name"><p><b>'+esc(state.right.name)+'</b><span>'+esc(state.right.english)+'</span></p><i>B</i></div></div><div class="sheet-grid">'+profile("left")+'<section class="center">'+img("pairImage","A + B 이미지","pair-image")+(state.visible.pair?'<div class="pair-block"><h3><b>P</b>페어 특징</h3>'+lines(state.pairText).map(function(x){return'<p>'+esc(x)+'</p>'}).join("")+'</div>':"")+'</section>'+profile("right")+'</div>';q("#sheet").innerHTML=h;q("#sheet").onchange=function(e){if(e.target.type==="file"){var box=e.target.closest("[data-image]"),f=e.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(){set(box.dataset.image,r.result)};r.readAsDataURL(f);}};}
  q("#previewBtn").onclick=function(){q(".app").classList.toggle("preview");q("#previewBtn").textContent=q(".app").classList.contains("preview")?"편집하기":"미리보기"};q("#printBtn").onclick=function(){window.print()};q("#saveDataBtn").onclick=function(){var b=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=(state.pairName||"WeLog")+".json";a.click();URL.revokeObjectURL(a.href)};q("#loadData").onchange=function(e){var f=e.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(){try{state=JSON.parse(r.result);persist();renderControls();renderSheet()}catch(e){alert("WeLog 저장 파일이 아닙니다.")}};r.readAsText(f)};renderTabs();renderControls();renderSheet();
})();
