(function(){
  var clone=function(v){return JSON.parse(JSON.stringify(v))};
  var blank=function(palette){return{name:"Name",quote:"한마디를 입력해 주세요.",gender:"-",age:"-",animal:"-",image:"",palette:palette,appearance:"이 특징은 기억해주세요.",outfitOk:true,colorOk:true};};
  var initial={pairName:"PAIR NAME",catchphrase:"PAIR CONTENTS",commissionCredit:"커미션 출처를 입력해 주세요.",centerMode:"combined",pairImage:"",pairImageLeft:"",pairImageRight:"",left:blank(["#2d2b28","#77726b","#b7b2aa","#efede8"]),right:blank(["#5e5a54","#918d86","#cfc9c0","#fbfaf8"]),pairColor:{mode:"gradient",color1:"#2d2b28",color2:"#918d86",angle:135},font:"Pretendard",paper:"#ffffff",imageEdits:{},visible:{palette:true,quote:true,profile:true,appearance:true,commission:true}};
  var raw=localStorage.getItem("welog-pair-sheet-v4"),state=raw?JSON.parse(raw):clone(initial),tab="main",characterSide="left",editingImagePath="",editingImageData="";
  function normalize(s){s.pairColor=s.pairColor||clone(initial.pairColor);if(s.pairColor.mode==="solid"&&s.pairColor.color1==="#2d2b28")s.pairColor.mode="gradient";if(s.pairColor.color1==="#39342f")s.pairColor.color1="#2d2b28";if(s.pairColor.color2==="#8d7965")s.pairColor.color2="#918d86";s.font=s.font||"Pretendard";s.centerMode=s.centerMode||"combined";s.pairImageLeft=s.pairImageLeft||"";s.pairImageRight=s.pairImageRight||"";s.imageEdits=s.imageEdits||{};s.visible=s.visible||clone(initial.visible);if(s.visible.commission===undefined)s.visible.commission=true;["left","right"].forEach(function(k){s[k].palette=s[k].palette||clone(initial[k].palette);if(!s[k].gender||s[k].gender==="Gender")s[k].gender="-";if(!s[k].age||s[k].age==="Age")s[k].age="-";if(!s[k].animal||s[k].animal==="Animal")s[k].animal="-";if(!s[k].appearance||s[k].appearance==="외관을 자유롭게 기록해 주세요.")s[k].appearance="이 특징은 기억해주세요.";s[k].outfitNote=s[k].outfitNote||"의상 간소화 OK";s[k].colorNote=s[k].colorNote||"색감 변형 OK";s[k].credit=s[k].credit||"커미션 출처를 입력해 주세요."});return s}state=normalize(state);
  state.commissionCredit=state.commissionCredit||(state.right&&state.right.credit)||(state.left&&state.left.credit)||"커미션 출처를 입력해 주세요.";
  ["left","right"].forEach(function(k){if(state[k].outfitOk===undefined)state[k].outfitOk=true;if(state[k].colorOk===undefined)state[k].colorOk=true});
  var tabs=[["main","M","MAIN"],["character","C","캐릭터"],["check","✓","체크"]];
  var q=function(s){return document.querySelector(s)},esc=function(v){return String(v||"").replace(/[&<>\"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c]})},lines=function(v){return String(v||"").split("\n").filter(Boolean)};
  function persist(){localStorage.setItem("welog-pair-sheet-v4",JSON.stringify(state))}
  function get(path){return path.split(".").reduce(function(o,k){return o[k]},state)}
  function set(path,value){var p=path.split("."),o=state;p.slice(0,-1).forEach(function(k){o=o[k]});o[p[p.length-1]]=value;persist();renderSheet()}
  function input(label,path,area){return'<label class="control"><span>'+label+'</span>'+(area?'<textarea data-path="'+path+'">'+esc(get(path))+'</textarea>':'<input data-path="'+path+'" value="'+esc(get(path))+'">')+'</label>'}
  function boolCheck(path,label){return'<label class="check commission-check"><input type="checkbox" data-bool-path="'+path+'" '+(get(path)?"checked":"")+'><span>'+label+'</span></label>'}
  function color(label,path){return'<label class="color"><span>'+label+'</span><input type="color" data-path="'+path+'" value="'+get(path)+'"></label>'}
  function paletteControls(side){return'<h3>컬러 팔레트</h3><div class="palette-controls">'+state[side].palette.map(function(v,i){return'<input aria-label="팔레트 '+(i+1)+'" type="color" data-path="'+side+'.palette.'+i+'" value="'+v+'">'}).join("")+'</div>'}
  function fontSelect(){var fonts=[["Pretendard","Pretendard"],["Noto Sans KR","Noto Sans KR"],["KoPub Dotum Light","KoPubWorld 돋움 Light"],["KoPub Dotum Medium","KoPubWorld 돋움 Medium"],["KoPub Dotum Bold","KoPubWorld 돋움 Bold"],["KoPub Batang Light","KoPubWorld 바탕 Light"],["KoPub Batang Medium","KoPubWorld 바탕 Medium"],["KoPub Batang Bold","KoPubWorld 바탕 Bold"]];return'<label class="select"><span>전체 폰트</span><select data-path="font">'+fonts.map(function(x){return'<option value="'+x[0]+'" '+(state.font===x[0]?"selected":"")+'>'+x[1]+'</option>'}).join("")+'</select></label>'}
  function mainColors(){var gradient=state.pairColor.mode==="gradient";return'<h3>페어 색상</h3><div class="mode-switch"><button type="button" data-pair-mode="solid" class="'+(!gradient?"on":"")+'">단색</button><button type="button" data-pair-mode="gradient" class="'+(gradient?"on":"")+'">그라데이션</button></div><div class="pair-color-row">'+color("첫 번째 색상","pairColor.color1")+(gradient?color("두 번째 색상","pairColor.color2"):"")+'</div>'+(gradient?'<label class="control gradient-angle-control"><span>그라데이션 기울기</span><div class="angle-row"><input type="range" min="0" max="360" data-path="pairColor.angle" value="'+state.pairColor.angle+'"><b>'+state.pairColor.angle+'°</b></div></label>':"")}
  function imageButton(path,label){return'<button type="button" class="image-edit-button" data-edit-image="'+path+'"><b>'+label+'</b><span>이미지 수정</span></button>'}
  function mainImages(){var split=state.centerMode==="split";return'<h3>이미지 수정</h3><div class="center-mode-check"><label><input type="radio" name="centerMode" data-center-mode="combined" '+(!split?"checked":"")+'>합본 (1장)</label><label><input type="radio" name="centerMode" data-center-mode="split" '+(split?"checked":"")+'>분리 (2장)</label></div><div class="image-button-grid">'+imageButton("left.image","A 이미지")+imageButton("right.image","B 이미지")+(split?imageButton("pairImageLeft","이미지")+imageButton("pairImageRight","이미지"):imageButton("pairImage","이미지"))+'</div>'}
  function slotData(){var data=clone(state);data.pairImage="";data.pairImageLeft="";data.pairImageRight="";data.left.image="";data.right.image="";return data}
  function slots(){var h='<div class="slots">';for(var i=1;i<=5;i++){var item=JSON.parse(localStorage.getItem("welog-slot-"+i)||"null"),name=item&&item.name?item.name:"슬롯 "+i;h+='<div class="slot"><span>0'+i+'</span><input class="slot-name" data-slot-name="'+i+'" value="'+esc(name)+'"><button data-slot-save="'+i+'">저장</button><button data-slot-load="'+i+'" '+(item?"":"disabled")+'>불러오기</button><button class="slot-delete" data-slot-delete="'+i+'" '+(item?"":"disabled")+'>×</button></div>'}return h+'</div>'}
  function renderSlotPanel(){q("#slotPanel").innerHTML=slots()}
  function renderTabs(){q("#tabs").innerHTML=tabs.map(function(t){return'<button data-tab="'+t[0]+'" class="'+(tab===t[0]?"on":"")+'"><b>'+t[1]+'</b><small>'+t[2]+'</small></button>'}).join("");q("#tabs").onclick=function(e){var b=e.target.closest("button");if(b){tab=b.dataset.tab;renderTabs();renderControls()}}}
  function renderControls(){var h="",side;
    if(tab==="main")h='<p class="section-label">MAIN</p><h2>메인 설정</h2>'+input("페어명","pairName")+input("캐치프레이즈","catchphrase")+fontSelect()+mainColors()+mainImages()+input("커미션 출처","commissionCredit",true);
    if(tab==="character"){side=characterSide;h='<p class="section-label">CHARACTER</p><h2>캐릭터</h2><div class="character-switch"><button type="button" data-character-side="left" class="'+(side==="left"?"on":"")+'">A 캐릭터</button><button type="button" data-character-side="right" class="'+(side==="right"?"on":"")+'">B 캐릭터</button></div>'+input("이름",side+".name")+input("한마디",side+".quote",true)+paletteControls(side)+'<div class="three">'+input("성별",side+".gender")+input("나이",side+".age")+input("동물화",side+".animal")+'</div>'+input("외관",side+".appearance",true)}
    if(tab==="check"){var opts=[["palette","컬러 팔레트"],["quote","한마디"],["profile","기본 프로필"],["appearance","외관"],["commission","커미션 안내·출처"]];h='<p class="section-label">CHECK</p><h2>체크</h2><p class="hint">체크를 해제한 항목은 결과에서도 생략됩니다.</p>'+opts.map(function(x){return'<label class="check"><input type="checkbox" data-visible="'+x[0]+'" '+(state.visible[x[0]]?"checked":"")+'><span>'+x[1]+'</span></label>'}).join("")+'<h3>캐릭터 A 커미션 안내</h3>'+boolCheck("left.outfitOk","의상 간소화 OK")+boolCheck("left.colorOk","색감 변형 OK")+'<h3>캐릭터 B 커미션 안내</h3>'+boolCheck("right.outfitOk","의상 간소화 OK")+boolCheck("right.colorOk","색감 변형 OK")+'<button class="reset" id="resetBtn">전체 초기화</button>'}
    q("#controls").innerHTML=h;
    q("#controls").oninput=function(e){if(e.target.dataset.path){set(e.target.dataset.path,e.target.type==="range"?Number(e.target.value):e.target.value);if(e.target.type==="range")renderControls()}if(e.target.dataset.boolPath)set(e.target.dataset.boolPath,e.target.checked);if(e.target.dataset.visible){state.visible[e.target.dataset.visible]=e.target.checked;persist();renderSheet()}};
    q("#controls").onclick=function(e){var edit=e.target.closest("[data-edit-image]");if(edit)openImageEditor(edit.dataset.editImage);if(e.target.dataset.characterSide){characterSide=e.target.dataset.characterSide;renderControls()}if(e.target.dataset.pairMode){state.pairColor.mode=e.target.dataset.pairMode;persist();renderControls();renderSheet()}if(e.target.dataset.centerMode){state.centerMode=e.target.dataset.centerMode;persist();renderControls();renderSheet()}if(e.target.id==="resetBtn"&&confirm("전체 내용을 초기화할까요?")){state=clone(initial);persist();renderControls();renderSheet()}}
  }
  function img(path,label,cls){var v=get(path),ed=state.imageEdits[path]||{scale:100,x:50,y:50};return'<button type="button" class="img '+cls+'" data-edit-image="'+path+'">'+(v?'<img src="'+v+'" alt="" style="transform:scale('+(ed.scale/100)+');transform-origin:'+ed.x+'% '+ed.y+'%;object-position:'+ed.x+'% '+ed.y+'%">':'<span>＋<small>이미지</small></span>')+'</button>'}
  function textBlock(p){return'<div class="text-block"><h3>외관</h3>'+lines(p.appearance).map(function(x){return'<p>'+esc(x)+'</p>'}).join("")+'</div>'}
  function commissionBlock(p,side){return'<div class="commission-block"><div>'+(p.outfitOk?'<span>의상 간소화 OK</span>':'')+(p.colorOk?'<span>색감 변형 OK</span>':'')+'</div>'+(side==="right"?'<small>COMMISSION</small><b>'+esc(state.commissionCredit)+'</b>':'')+'</div>'}
  function profile(side){var p=state[side],v=state.visible,h='<article class="profile '+side+'"><div class="profile-title"><b>'+esc(p.name)+'</b></div>'+img(side+".image","이미지","main-image");if(v.palette)h+='<div class="palette-bar">'+p.palette.map(function(c){return'<i style="background:'+c+'"></i>'}).join("")+'</div>';if(v.quote)h+='<blockquote class="quote">“'+esc(p.quote)+'”</blockquote>';if(v.profile)h+='<div class="facts"><div><span>성별</span><b>'+esc(p.gender)+'</b></div><div><span>나이</span><b>'+esc(p.age)+'</b></div><div><span>동물화</span><b>'+esc(p.animal)+'</b></div></div>';if(v.appearance)h+=textBlock(p);if(v.commission)h+=commissionBlock(p,side);return h+'</article>'}
  function centerImages(){return state.centerMode==="split"?'<div class="pair-split">'+img("pairImageLeft","이미지","pair-image")+img("pairImageRight","이미지","pair-image")+'</div>':img("pairImage","이미지","pair-image")}
  function renderSheet(){var bg=state.pairColor.mode==="gradient"?"linear-gradient("+state.pairColor.angle+"deg,"+state.pairColor.color1+","+state.pairColor.color2+")":state.pairColor.color1;document.documentElement.style.setProperty("--a",state.left.palette[0]);document.documentElement.style.setProperty("--b",state.right.palette[0]);document.documentElement.style.setProperty("--pair-bg",bg);document.documentElement.style.setProperty("--app-font",'"'+state.font+'","Noto Sans KR",sans-serif');document.documentElement.style.setProperty("--paper",state.paper);var h='<div class="sheet-head"><div><i>A</i><p><b>'+esc(state.left.name)+'</b></p></div><section><b>'+esc(state.pairName)+'</b><span>'+esc(state.catchphrase)+'</span></section><div class="right-name"><p><b>'+esc(state.right.name)+'</b></p><i>B</i></div></div><div class="sheet-grid">'+profile("left")+'<section class="center">'+centerImages()+'</section>'+profile("right")+'</div>';q("#sheet").innerHTML=h;q("#sheet").onclick=function(e){var b=e.target.closest("[data-edit-image]");if(b)openImageEditor(b.dataset.editImage)}}
  function updateImagePreview(){var scale=Number(q("#imageScale").value),x=Number(q("#imageX").value),y=Number(q("#imageY").value),im=q("#imageEditorPreview");im.src=editingImageData||"";im.style.transform="scale("+(scale/100)+")";im.style.transformOrigin=x+"% "+y+"%";im.style.objectPosition=x+"% "+y+"%";q("#imageScaleValue").textContent=scale+"%";q("#imageXValue").textContent=x;q("#imageYValue").textContent=y}
  function openImageEditor(path){editingImagePath=path;editingImageData=get(path)||"";var ed=state.imageEdits[path]||{scale:100,x:50,y:50};q("#imageScale").value=ed.scale;q("#imageX").value=ed.x;q("#imageY").value=ed.y;updateImagePreview();q("#imageModal").hidden=false}
  function closeImageEditor(){q("#imageModal").hidden=true}
  function closeSlots(){q("#slotDrawer").hidden=true}q("#slotOpenBtn").onclick=function(){renderSlotPanel();q("#slotDrawer").hidden=false};q("#slotCloseBtn").onclick=closeSlots;q("#slotBackdrop").onclick=closeSlots;q("#slotPanel").onclick=function(e){var save=e.target.dataset.slotSave;if(save){var name=q('[data-slot-name="'+save+'"]').value.trim()||"슬롯 "+save;localStorage.setItem("welog-slot-"+save,JSON.stringify({name:name,data:slotData()}));renderSlotPanel()}var load=e.target.dataset.slotLoad;if(load){var item=JSON.parse(localStorage.getItem("welog-slot-"+load));var images={pairImage:state.pairImage,pairImageLeft:state.pairImageLeft,pairImageRight:state.pairImageRight,left:state.left.image,right:state.right.image};state=normalize(clone(item.data));state.pairImage=images.pairImage;state.pairImageLeft=images.pairImageLeft;state.pairImageRight=images.pairImageRight;state.left.image=images.left;state.right.image=images.right;persist();renderControls();renderSheet();closeSlots()}var del=e.target.dataset.slotDelete;if(del&&confirm("이 슬롯을 비울까요?")){localStorage.removeItem("welog-slot-"+del);renderSlotPanel()}};
  q("#imageEditorClose").onclick=closeImageEditor;q("#imageModalBackdrop").onclick=closeImageEditor;["#imageScale","#imageX","#imageY"].forEach(function(id){q(id).oninput=updateImagePreview});q("#imageEditorFile").onchange=function(e){var f=e.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(){editingImageData=r.result;updateImagePreview()};r.readAsDataURL(f)};q("#imageEditorApply").onclick=function(){set(editingImagePath,editingImageData);state.imageEdits[editingImagePath]={scale:Number(q("#imageScale").value),x:Number(q("#imageX").value),y:Number(q("#imageY").value)};persist();renderSheet();closeImageEditor()};q("#imageEditorRemove").onclick=function(){set(editingImagePath,"");delete state.imageEdits[editingImagePath];persist();renderSheet();closeImageEditor()};
  var zoom=100;function applyZoom(){q("#sheet").style.transform="scale("+(zoom/100)+")";q("#sheet").style.transformOrigin="top center";q("#zoomValue").textContent=zoom+"%"}q("#zoomOutBtn").onclick=function(){zoom=Math.max(50,zoom-10);applyZoom()};q("#zoomInBtn").onclick=function(){zoom=Math.min(150,zoom+10);applyZoom()};q("#zoomResetBtn").onclick=function(){zoom=100;applyZoom()};q("#helpOpenBtn").onclick=function(){alert("MAIN에서 페어 색상과 이미지를 설정하고, 캐릭터 탭에서 A/B를 전환해 정보를 입력하세요. 체크 탭에서는 표시할 항목을 선택할 수 있습니다.")};
  q("#previewBtn").onclick=function(){q(".app").classList.toggle("preview");q("#previewBtn").textContent=q(".app").classList.contains("preview")?"편집하기":"미리보기"};q("#printBtn").onclick=function(){window.print()};q("#saveDataBtn").onclick=function(){var b=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=(state.pairName||"WeLog")+".json";a.click();URL.revokeObjectURL(a.href)};q("#loadData").onchange=function(e){var f=e.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(){try{state=normalize(JSON.parse(r.result));persist();renderControls();renderSheet()}catch(e){alert("WeLog 저장 파일이 아닙니다.")}};r.readAsText(f)};renderTabs();renderControls();renderSheet();
})();
