(function(){
  var clone=function(v){return JSON.parse(JSON.stringify(v))};
  var blank=function(palette){return{name:"Name",quote:"한마디를 입력해 주세요.",gender:"Gender",age:"Age",animal:"Animal",image:"",palette:palette,appearanceTitle:"이 특징은 기억해주세요.",appearance:"외관을 자유롭게 기록해 주세요.",outfitNote:"의상 간소화 OK",colorNote:"색감 변형 OK",credit:"커미션 출처를 입력해 주세요."};};
  var initial={pairName:"PAIR NAME",catchphrase:"PAIR CONTENTS",centerMode:"combined",pairImage:"",pairImageLeft:"",pairImageRight:"",left:blank(["#2d2b28","#77726b","#b7b2aa","#efede8"]),right:blank(["#5e5a54","#918d86","#cfc9c0","#fbfaf8"]),pairColor:{mode:"solid",color1:"#2d2b28",color2:"#918d86",angle:135},font:"Pretendard",paper:"#ffffff",visible:{palette:true,quote:true,profile:true,appearance:true,commission:true}};
  var raw=localStorage.getItem("welog-pair-sheet-v4"),state=raw?JSON.parse(raw):clone(initial),tab="main";
  function normalize(s){s.pairColor=s.pairColor||clone(initial.pairColor);if(s.pairColor.color1==="#39342f")s.pairColor.color1="#2d2b28";if(s.pairColor.color2==="#8d7965")s.pairColor.color2="#918d86";s.font=s.font||"Pretendard";s.centerMode=s.centerMode||"combined";s.pairImageLeft=s.pairImageLeft||"";s.pairImageRight=s.pairImageRight||"";s.visible=s.visible||clone(initial.visible);if(s.visible.commission===undefined)s.visible.commission=true;["left","right"].forEach(function(k){s[k].palette=s[k].palette||clone(initial[k].palette);s[k].appearanceTitle=s[k].appearanceTitle||"이 특징은 기억해주세요.";s[k].outfitNote=s[k].outfitNote||"의상 간소화 OK";s[k].colorNote=s[k].colorNote||"색감 변형 OK";s[k].credit=s[k].credit||"커미션 출처를 입력해 주세요."});return s}state=normalize(state);
  var tabs=[["main","M","MAIN"],["left","A","캐릭터 A"],["right","B","캐릭터 B"],["image","I","이미지"],["color","C","컬러"],["omit","✓","생략"]];
  var q=function(s){return document.querySelector(s)},esc=function(v){return String(v||"").replace(/[&<>\"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c]})},lines=function(v){return String(v||"").split("\n").filter(Boolean)};
  function persist(){localStorage.setItem("welog-pair-sheet-v4",JSON.stringify(state))}
  function get(path){return path.split(".").reduce(function(o,k){return o[k]},state)}
  function set(path,value){var p=path.split("."),o=state;p.slice(0,-1).forEach(function(k){o=o[k]});o[p[p.length-1]]=value;persist();renderSheet()}
  function input(label,path,area){return'<label class="control"><span>'+label+'</span>'+(area?'<textarea data-path="'+path+'">'+esc(get(path))+'</textarea>':'<input data-path="'+path+'" value="'+esc(get(path))+'">')+'</label>'}
  function color(label,path){return'<label class="color"><span>'+label+'</span><input type="color" data-path="'+path+'" value="'+get(path)+'"></label>'}
  function paletteControls(side){return'<h3>컬러 팔레트</h3><div class="palette-controls">'+state[side].palette.map(function(v,i){return'<input aria-label="팔레트 '+(i+1)+'" type="color" data-path="'+side+'.palette.'+i+'" value="'+v+'">'}).join("")+'</div>'}
  function fontSelect(){var fonts=[["Pretendard","Pretendard"],["Noto Sans KR","Noto Sans KR"],["KoPub Dotum Light","KoPubWorld 돋움 Light"],["KoPub Dotum Medium","KoPubWorld 돋움 Medium"],["KoPub Dotum Bold","KoPubWorld 돋움 Bold"],["KoPub Batang Light","KoPubWorld 바탕 Light"],["KoPub Batang Medium","KoPubWorld 바탕 Medium"],["KoPub Batang Bold","KoPubWorld 바탕 Bold"]];return'<label class="select"><span>전체 폰트</span><select data-path="font">'+fonts.map(function(x){return'<option value="'+x[0]+'" '+(state.font===x[0]?"selected":"")+'>'+x[1]+'</option>'}).join("")+'</select></label>'}
  function mainColors(){var gradient=state.pairColor.mode==="gradient";return'<h3>페어 색상</h3><div class="mode-switch"><button type="button" data-pair-mode="solid" class="'+(!gradient?"on":"")+'">단색</button><button type="button" data-pair-mode="gradient" class="'+(gradient?"on":"")+'">그라데이션</button></div>'+color("첫 번째 색상","pairColor.color1")+(gradient?color("두 번째 색상","pairColor.color2")+'<label class="control"><span>그라데이션 기울기</span><div class="angle-row"><input type="range" min="0" max="360" data-path="pairColor.angle" value="'+state.pairColor.angle+'"><b>'+state.pairColor.angle+'°</b></div></label>':"")}
  function slotData(){var data=clone(state);data.pairImage="";data.pairImageLeft="";data.pairImageRight="";data.left.image="";data.right.image="";return data}
  function slots(){var h='<h3>작업 슬롯</h3><p class="hint">슬롯에는 이미지가 아닌 텍스트와 설정만 저장됩니다.</p><div class="slots">';for(var i=1;i<=5;i++){var item=JSON.parse(localStorage.getItem("welog-slot-"+i)||"null"),name=item&&item.name?item.name:"슬롯 "+i;h+='<div class="slot"><span>0'+i+'</span><input class="slot-name" data-slot-name="'+i+'" value="'+esc(name)+'"><button data-slot-save="'+i+'">저장</button><button data-slot-load="'+i+'" '+(item?"":"disabled")+'>불러오기</button><button class="slot-delete" data-slot-delete="'+i+'" '+(item?"":"disabled")+'>×</button></div>'}return h+'</div>'}
  function renderTabs(){q("#tabs").innerHTML=tabs.map(function(t){return'<button data-tab="'+t[0]+'" class="'+(tab===t[0]?"on":"")+'"><b>'+t[1]+'</b><small>'+t[2]+'</small></button>'}).join("");q("#tabs").onclick=function(e){var b=e.target.closest("button");if(b){tab=b.dataset.tab;renderTabs();renderControls()}}}
  function renderControls(){var h="",side;
    if(tab==="main")h='<p class="section-label">MAIN</p><h2>메인 설정</h2>'+input("페어명","pairName")+input("캐치프레이즈","catchphrase")+fontSelect()+mainColors()+slots();
    if(tab==="left"||tab==="right"){side=tab;h='<p class="section-label">CHARACTER '+(side==="left"?"A":"B")+'</p><h2>'+esc(state[side].name)+'</h2>'+input("이름",side+".name")+input("한마디",side+".quote",true)+paletteControls(side)+'<div class="two">'+input("젠더",side+".gender")+input("나이",side+".age")+input("동물화",side+".animal")+'</div>'+input("외관 안내",side+".appearanceTitle")+input("외관",side+".appearance",true)+'<h3>커미션 안내</h3>'+input("의상 간소화",side+".outfitNote")+input("색감 변형",side+".colorNote")+input("커미션 출처",side+".credit")}
    if(tab==="image")h='<p class="section-label">IMAGE</p><h2>이미지</h2><h3>가운데 이미지 구성</h3><div class="mode-switch"><button type="button" data-center-mode="combined" class="'+(state.centerMode==="combined"?"on":"")+'">합본 1장</button><button type="button" data-center-mode="split" class="'+(state.centerMode==="split"?"on":"")+'">분리 2장</button></div><p class="hint">시트 안의 이미지 칸을 클릭해 이미지를 넣으세요.</p><button class="remove" data-remove="center">가운데 이미지 삭제</button><button class="remove" data-remove="left">A 메인 이미지 삭제</button><button class="remove" data-remove="right">B 메인 이미지 삭제</button>';
    if(tab==="color")h='<p class="section-label">COLOR</p><h2>시트 컬러</h2>'+color("시트 배경","paper")+'<p class="hint">페어 색상은 MAIN에서, 캐릭터 팔레트는 A/B 메뉴에서 조정합니다.</p>';
    if(tab==="omit"){var opts=[["palette","컬러 팔레트"],["quote","한마디"],["profile","기본 프로필"],["appearance","외관"],["commission","커미션 안내"]];h='<p class="section-label">SHOW / HIDE</p><h2>표시할 항목</h2><p class="hint">체크를 해제한 항목은 결과에서도 생략됩니다.</p>'+opts.map(function(x){return'<label class="check"><input type="checkbox" data-visible="'+x[0]+'" '+(state.visible[x[0]]?"checked":"")+'><span>'+x[1]+'</span></label>'}).join("")+'<button class="reset" id="resetBtn">전체 초기화</button>'}
    q("#controls").innerHTML=h;
    q("#controls").oninput=function(e){if(e.target.dataset.path){set(e.target.dataset.path,e.target.type==="range"?Number(e.target.value):e.target.value);if(e.target.type==="range")renderControls()}if(e.target.dataset.visible){state.visible[e.target.dataset.visible]=e.target.checked;persist();renderSheet()}};
    q("#controls").onclick=function(e){var r=e.target.dataset.remove;if(r){if(r==="center"){state.pairImage="";state.pairImageLeft="";state.pairImageRight=""}else state[r].image="";persist();renderSheet()}if(e.target.dataset.pairMode){state.pairColor.mode=e.target.dataset.pairMode;persist();renderControls();renderSheet()}if(e.target.dataset.centerMode){state.centerMode=e.target.dataset.centerMode;persist();renderControls();renderSheet()}var save=e.target.dataset.slotSave;if(save){var name=q('[data-slot-name="'+save+'"]').value.trim()||"슬롯 "+save;localStorage.setItem("welog-slot-"+save,JSON.stringify({name:name,data:slotData()}));renderControls()}var load=e.target.dataset.slotLoad;if(load){var item=JSON.parse(localStorage.getItem("welog-slot-"+load));var images={pairImage:state.pairImage,pairImageLeft:state.pairImageLeft,pairImageRight:state.pairImageRight,left:state.left.image,right:state.right.image};state=normalize(clone(item.data));state.pairImage=images.pairImage;state.pairImageLeft=images.pairImageLeft;state.pairImageRight=images.pairImageRight;state.left.image=images.left;state.right.image=images.right;persist();renderControls();renderSheet()}var del=e.target.dataset.slotDelete;if(del&&confirm("이 슬롯을 비울까요?")){localStorage.removeItem("welog-slot-"+del);renderControls()}if(e.target.id==="resetBtn"&&confirm("전체 내용을 초기화할까요?")){state=clone(initial);persist();renderControls();renderSheet()}}
  }
  function img(path,label,cls){var v=get(path);return'<label class="img '+cls+'" data-image="'+path+'">'+(v?'<img src="'+v+'" alt="">':'<span>＋<small>'+label+'</small></span>')+'<input type="file" accept="image/*"></label>'}
  function textBlock(p){return'<div class="text-block"><h3>외관</h3><strong>'+esc(p.appearanceTitle)+'</strong>'+lines(p.appearance).map(function(x){return'<p>'+esc(x)+'</p>'}).join("")+'</div>'}
  function commissionBlock(p){return'<div class="commission-block"><div><span>'+esc(p.outfitNote)+'</span><span>'+esc(p.colorNote)+'</span></div><small>COMMISSION</small><b>'+esc(p.credit)+'</b></div>'}
  function profile(side){var p=state[side],v=state.visible,h='<article class="profile '+side+'"><div class="profile-title"><b>'+esc(p.name)+'</b></div>'+img(side+".image","메인 이미지","main-image");if(v.palette)h+='<div class="palette-bar">'+p.palette.map(function(c){return'<i style="background:'+c+'"></i>'}).join("")+'</div>';if(v.quote)h+='<blockquote class="quote">“'+esc(p.quote)+'”</blockquote>';if(v.profile)h+='<div class="facts"><div><span>젠더</span><b>'+esc(p.gender)+'</b></div><div><span>나이</span><b>'+esc(p.age)+'</b></div><div><span>동물화</span><b>'+esc(p.animal)+'</b></div></div>';if(v.appearance)h+=textBlock(p);if(v.commission)h+=commissionBlock(p);return h+'</article>'}
  function centerImages(){return state.centerMode==="split"?'<div class="pair-split">'+img("pairImageLeft","A 이미지","pair-image")+img("pairImageRight","B 이미지","pair-image")+'</div>':img("pairImage","A + B 이미지","pair-image")}
  function renderSheet(){var bg=state.pairColor.mode==="gradient"?"linear-gradient("+state.pairColor.angle+"deg,"+state.pairColor.color1+","+state.pairColor.color2+")":state.pairColor.color1;document.documentElement.style.setProperty("--a",state.left.palette[0]);document.documentElement.style.setProperty("--b",state.right.palette[0]);document.documentElement.style.setProperty("--pair-bg",bg);document.documentElement.style.setProperty("--app-font",'"'+state.font+'","Noto Sans KR",sans-serif');document.documentElement.style.setProperty("--paper",state.paper);var h='<div class="sheet-head"><div><i>A</i><p><b>'+esc(state.left.name)+'</b></p></div><section><b>'+esc(state.pairName)+'</b><span>'+esc(state.catchphrase)+'</span></section><div class="right-name"><p><b>'+esc(state.right.name)+'</b></p><i>B</i></div></div><div class="sheet-grid">'+profile("left")+'<section class="center">'+centerImages()+'</section>'+profile("right")+'</div>';q("#sheet").innerHTML=h;q("#sheet").onchange=function(e){if(e.target.type==="file"){var box=e.target.closest("[data-image]"),f=e.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(){set(box.dataset.image,r.result)};r.readAsDataURL(f)}}}
  q("#previewBtn").onclick=function(){q(".app").classList.toggle("preview");q("#previewBtn").textContent=q(".app").classList.contains("preview")?"편집하기":"미리보기"};q("#printBtn").onclick=function(){window.print()};q("#saveDataBtn").onclick=function(){var b=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=(state.pairName||"WeLog")+".json";a.click();URL.revokeObjectURL(a.href)};q("#loadData").onchange=function(e){var f=e.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(){try{state=normalize(JSON.parse(r.result));persist();renderControls();renderSheet()}catch(e){alert("WeLog 저장 파일이 아닙니다.")}};r.readAsText(f)};renderTabs();renderControls();renderSheet();
})();
