(function(){
  var KEY="welog-pair-sheet-v4",DB="welog-fonts-v2",STORE="fonts",controls=document.querySelector("#controls"),sheet=document.querySelector("#sheet");
  function read(){try{return JSON.parse(localStorage.getItem(KEY)||"{}")||{}}catch(e){return{}}}
  function write(s){try{localStorage.setItem(KEY,JSON.stringify(s))}catch(e){}}
  function esc(v){return String(v||"").replace(/[&<>\"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c]})}
  function side(){var b=controls&&controls.querySelector("[data-character-side].on");return b?b.dataset.characterSide:"left"}
  function fontStack(name){if(!name||name==="Pretendard"||name==="__default__")return 'Pretendard,"Noto Sans KR",sans-serif';if(name==="__system__")return 'system-ui,-apple-system,"Segoe UI","Noto Sans KR",sans-serif';return '"'+String(name).replace(/"/g,"")+'","Noto Sans KR",sans-serif'}
  function applyFont(){if(!sheet)return;var s=read(),stack=fontStack(s.font);sheet.style.setProperty("--welog-font",stack);sheet.style.setProperty("font-family",stack,"important")}
  function openDB(){return new Promise(function(ok,no){var r=indexedDB.open(DB,1);r.onupgradeneeded=function(){if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:"name"})};r.onsuccess=function(){ok(r.result)};r.onerror=function(){no(r.error)}})}
  function allFonts(){return openDB().then(function(db){return new Promise(function(ok,no){var r=db.transaction(STORE,"readonly").objectStore(STORE).getAll();r.onsuccess=function(){ok(r.result||[])};r.onerror=function(){no(r.error)}})})}
  function putFont(x){return openDB().then(function(db){return new Promise(function(ok,no){var tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(x);tx.oncomplete=ok;tx.onerror=function(){no(tx.error)}})})}
  function loadFont(x){if(!x||!x.data)return Promise.resolve();var face=new FontFace(x.name,x.data);return face.load().then(function(f){document.fonts.add(f)}).catch(function(){})}
  function pairControls(){if(!controls||!controls.querySelector(".layout-ratio-controls")||controls.querySelector(".pair-meta-editor"))return;var s=read(),box=document.createElement("section");box.className="pair-meta-editor";box.innerHTML='<div class="pair-meta-editor-head"><b>페어명 표기</b><span>시트 상단에 표시됩니다.</span></div><label><span>페어명</span><input type="text" data-path="pairName" value="'+esc(s.pairName||"")+'"></label><label><span>기타 표기</span><input type="text" data-path="catchphrase" value="'+esc(s.catchphrase||"")+'"></label>';controls.querySelector(".layout-ratio-controls").insertAdjacentElement("beforebegin",box)}
  function characterControls(){if(!controls||!controls.querySelector(".character-switch"))return;var sd=side(),first=controls.querySelector(".rich-control"),old=controls.querySelector(".character-meta-editor");if(old&&old.dataset.side===sd)return;if(old)old.remove();if(!first)return;var s=read(),d=s[sd]||{},box=document.createElement("section");box.className="character-meta-editor";box.dataset.side=sd;box.innerHTML='<label><span>이름 외 별도 표기</span><input type="text" data-path="'+sd+'.subtitle" value="'+esc(d.subtitle||"")+'" placeholder="이름과 함께 표시할 문구"></label><div class="meta-color-row"><span></span><label><span>색상</span><input type="color" data-path="'+sd+'.subtitleColor" value="'+esc(d.subtitleColor||"#918d86")+'"></label></div>';first.insertAdjacentElement("afterend",box);var cb=controls.querySelector("[data-concept-side]");if(cb){cb.dataset.conceptToggle=sd;delete cb.dataset.conceptSide;var current=read(),dd=current[sd]||{};cb.checked=dd.showConcept!==undefined?!!dd.showConcept:(current.conceptSide===sd)}}
  function fontControls(){if(!controls||!controls.querySelector(".global-font-controls")||controls.querySelector(".font-extra-controls"))return;var s=read(),wrap=document.createElement("section");wrap.className="font-extra-controls";wrap.innerHTML='<div class="font-extra-head"><b>폰트 선택</b><span>기본·시스템·업로드 폰트</span></div><select data-stable-font><option value="__default__">기본 폰트 · Pretendard</option><option value="__system__">시스템 폰트</option></select><label class="font-upload-label"><b>폰트 업로드</b><small>TTF · OTF · WOFF · WOFF2</small><input type="file" data-font-upload accept=".ttf,.otf,.woff,.woff2,font/ttf,font/otf,font/woff,font/woff2"></label>';controls.querySelector(".global-font-controls").appendChild(wrap);allFonts().then(function(list){return Promise.all(list.map(loadFont)).then(function(){var sel=wrap.querySelector("[data-stable-font]");list.forEach(function(f){var o=document.createElement("option");o.value=f.name;o.textContent="업로드 · "+f.name;sel.appendChild(o)});sel.value=s.font==="Pretendard"?"__default__":(s.font||"__default__")})})}
  function enhancePair(){if(!sheet)return;var s=read(),grid=sheet.querySelector(".sheet-grid");if(!grid)return;var old=sheet.querySelector(".pair-title-display");if(old)old.remove();if(!(s.pairName||s.catchphrase))return;var h=document.createElement("header");h.className="pair-title-display";h.innerHTML=(s.pairName?'<b>'+esc(s.pairName)+'</b>':'')+(s.catchphrase?'<small>'+esc(s.catchphrase)+'</small>':'');sheet.insertBefore(h,grid)}
  function enhanceNames(){["left","right"].forEach(function(sd){var title=sheet&&sheet.querySelector(".profile."+sd+" .profile-title");if(!title)return;var d=(read()[sd]||{}),name=title.querySelector(":scope > b"),stack=title.querySelector(".profile-name-stack");if(!stack&&name){stack=document.createElement("div");stack.className="profile-name-stack";name.replaceWith(stack);stack.appendChild(name)}if(!stack)return;var sm=stack.querySelector(".profile-subtitle");if(!sm){sm=document.createElement("small");sm.className="profile-subtitle";stack.appendChild(sm)}sm.textContent=d.subtitle||"";sm.style.color=d.subtitleColor||"#918d86";sm.hidden=!d.subtitle})}
  function enhanceConcepts(){if(!sheet)return;var s=read();["left","right"].forEach(function(sd){var p=sheet.querySelector(".profile."+sd);if(!p)return;p.querySelectorAll(".concept-block").forEach(function(x){x.remove()});var d=s[sd]||{},show=d.showConcept!==undefined?!!d.showConcept:(s.conceptSide===sd);if(!show||!d.concept)return;var b=document.createElement("div");b.className="text-block concept-block";b.innerHTML='<h3>컨셉</h3><div class="formatted-lines">'+String(d.concept).split("\n").filter(Boolean).map(function(x){return'<p>'+esc(x)+'</p>'}).join("")+'</div>';var commission=p.querySelector(".commission-block");if(commission)p.insertBefore(b,commission);else p.appendChild(b)})}
  function enhance(){applyFont();enhancePair();enhanceNames();enhanceConcepts()}
  if(controls){controls.addEventListener("input",function(e){if(e.target.dataset.conceptToggle){var s=read(),sd=e.target.dataset.conceptToggle;s[sd]=s[sd]||{};s[sd].showConcept=e.target.checked;s.visible=s.visible||{};s.visible.concept=true;write(s);setTimeout(enhance,0)}if(e.target.dataset.stableFont){var s2=read(),v=e.target.value;s2.font=v==="__default__"?"Pretendard":v;write(s2);var orig=controls.querySelector('select[data-path="font"]');if(orig){orig.value=s2.font;orig.dispatchEvent(new Event("input",{bubbles:true}))}setTimeout(enhance,0)}},true);controls.addEventListener("change",function(e){if(e.target.dataset.stableFont){var s=read(),v=e.target.value;s.font=v==="__default__"?"Pretendard":v;write(s);setTimeout(enhance,0)}if(e.target.dataset.fontUpload!==undefined){var f=e.target.files&&e.target.files[0];if(!f)return;var reader=new FileReader();reader.onload=function(){var name=(f.name||"Custom Font").replace(/\.[^.]+$/,"");var data=reader.result;var face=new FontFace(name,data);face.load().then(function(ff){document.fonts.add(ff);return putFont({name:name,data:data})}).then(function(){var s=read();s.font=name;write(s);applyFont();var sel=controls.querySelector("[data-stable-font]");if(sel){var o=document.createElement("option");o.value=name;o.textContent="업로드 · "+name;sel.appendChild(o);sel.value=name}}).catch(function(){alert("폰트를 불러오지 못했습니다.")})};reader.readAsArrayBuffer(f);e.target.value=""}},true)}
  document.addEventListener("input",function(){setTimeout(enhance,0)},true);document.addEventListener("change",function(){setTimeout(enhance,0)},true);document.addEventListener("click",function(){setTimeout(function(){pairControls();characterControls();fontControls();enhance()},0)},true);
  var ob=controls&&new MutationObserver(function(){pairControls();characterControls();fontControls()});if(ob)ob.observe(controls,{childList:true,subtree:false});
  allFonts().then(function(list){return Promise.all(list.map(loadFont))}).finally(function(){pairControls();characterControls();fontControls();enhance()});
})();
