(function(){
  'use strict';
  var KEY='welog-pair-sheet-v4',DB='welog-fonts-v3',STORE='fonts';
  var controls=document.querySelector('#controls'),sheet=document.querySelector('#sheet');
  var loadedFonts=[];
  function read(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch(e){return{}}}
  function esc(v){return String(v||'').replace(/[&<>\"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}
  function currentSide(){var b=controls&&controls.querySelector('[data-character-side].on');return b?b.dataset.characterSide:'left'}
  function openDB(){return new Promise(function(ok,no){if(!window.indexedDB){ok(null);return}var r=indexedDB.open(DB,1);r.onupgradeneeded=function(){if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'name'})};r.onsuccess=function(){ok(r.result)};r.onerror=function(){no(r.error)}})}
  function allFonts(){return openDB().then(function(db){if(!db)return[];return new Promise(function(ok,no){var r=db.transaction(STORE,'readonly').objectStore(STORE).getAll();r.onsuccess=function(){ok(r.result||[])};r.onerror=function(){no(r.error)}})})}
  function putFont(x){return openDB().then(function(db){if(!db)throw new Error('IndexedDB unavailable');return new Promise(function(ok,no){var tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(x);tx.oncomplete=function(){ok()};tx.onerror=function(){no(tx.error)}})})}
  function loadFont(x){if(!x||!x.data||!window.FontFace)return Promise.resolve();try{var face=new FontFace(x.name,x.data);return face.load().then(function(f){document.fonts.add(f);if(loadedFonts.indexOf(x.name)<0)loadedFonts.push(x.name)}).catch(function(){})}catch(e){return Promise.resolve()}}
  function addUploadedFontOptions(select){if(!select)return;loadedFonts.forEach(function(name){if(Array.from(select.options).some(function(o){return o.value===name}))return;var op=document.createElement('option');op.value=name;op.textContent='업로드 · '+name;select.appendChild(op)});var wanted=read().font;if(wanted&&Array.from(select.options).some(function(o){return o.value===wanted}))select.value=wanted}
  function ensurePairControls(){if(!controls||!controls.querySelector('.layout-ratio-controls')||controls.querySelector('.pair-meta-editor'))return;var s=read(),box=document.createElement('section');box.className='pair-meta-editor';box.innerHTML='<div class="pair-meta-editor-head"><b>페어명</b><span>시트 상단에 크게 표시됩니다.</span></div><label><span>페어명</span><input type="text" data-path="pairName" value="'+esc(s.pairName||'')+'" placeholder="페어명을 입력해 주세요."></label><label><span>페어명 별도 표기</span><input type="text" data-path="catchphrase" value="'+esc(s.catchphrase||'')+'" placeholder="페어명 아래 작은 표기"></label>';controls.querySelector('.layout-ratio-controls').insertAdjacentElement('beforebegin',box)}
  function ensureCharacterControls(){if(!controls||!controls.querySelector('.character-switch'))return;var sd=currentSide(),old=controls.querySelector('.character-meta-editor');if(old&&old.dataset.side===sd)return;if(old)old.remove();var nameControl=controls.querySelector('.rich-control');if(!nameControl)return;var d=(read()[sd]||{}),box=document.createElement('section');box.className='character-meta-editor';box.dataset.side=sd;box.innerHTML='<label><span>이름 외 별도 표기</span><input type="text" data-path="'+sd+'.subtitle" value="'+esc(d.subtitle||'')+'" placeholder="이름 아래에 표시할 문구"></label>';nameControl.insertAdjacentElement('afterend',box)}
  function ensureFontControls(){if(!controls)return;var global=controls.querySelector('.global-font-controls');if(!global)return;var select=global.querySelector('select[data-path="font"]');if(select)addUploadedFontOptions(select);if(!global.querySelector('.font-upload-label')){var up=document.createElement('label');up.className='font-upload-label';up.innerHTML='<b>폰트 업로드</b><small>TTF · OTF · WOFF · WOFF2</small><input type="file" data-font-upload accept=".ttf,.otf,.woff,.woff2,font/ttf,font/otf,font/woff,font/woff2">';global.appendChild(up)}}
  function enhancePair(){if(!sheet)return;var s=read(),grid=sheet.querySelector('.sheet-grid');if(!grid)return;var head=sheet.querySelector('.pair-title-display');if(!head){head=document.createElement('header');head.className='pair-title-display';sheet.insertBefore(head,grid)}var name=s.pairName||'',sub=s.catchphrase||'';head.innerHTML=(name?'<b>'+esc(name)+'</b>':'')+(sub?'<small>'+esc(sub)+'</small>':'');head.hidden=!name&&!sub}
  function enhanceNames(){if(!sheet)return;var s=read();['left','right'].forEach(function(sd){var title=sheet.querySelector('.profile.'+sd+' .profile-title');if(!title)return;var d=s[sd]||{},name=title.querySelector(':scope > b'),stack=title.querySelector('.profile-name-stack');if(!stack&&name){stack=document.createElement('div');stack.className='profile-name-stack';name.replaceWith(stack);stack.appendChild(name)}if(!stack)return;var small=stack.querySelector('.profile-subtitle');if(!small){small=document.createElement('small');small.className='profile-subtitle';stack.appendChild(small)}small.textContent=d.subtitle||'';small.hidden=!d.subtitle})}
  function enhance(){enhancePair();enhanceNames()}
  function refreshControls(){ensurePairControls();ensureCharacterControls();ensureFontControls()}
  if(controls){
    controls.addEventListener('change',function(e){if(e.target.dataset.fontUpload!==undefined){var f=e.target.files&&e.target.files[0];if(!f)return;var reader=new FileReader();reader.onload=function(){var name=(f.name||'Custom Font').replace(/\.[^.]+$/,''),data=reader.result,face;try{face=new FontFace(name,data)}catch(err){alert('이 폰트 파일을 읽을 수 없습니다.');return}face.load().then(function(ff){document.fonts.add(ff);if(loadedFonts.indexOf(name)<0)loadedFonts.push(name);return putFont({name:name,data:data})}).then(function(){var sel=controls.querySelector('select[data-path="font"]');if(sel){addUploadedFontOptions(sel);sel.value=name;sel.dispatchEvent(new Event('input',{bubbles:true}));sel.dispatchEvent(new Event('change',{bubbles:true}))}}).catch(function(){alert('폰트를 불러오지 못했습니다.')})};reader.readAsArrayBuffer(f);e.target.value='';return}setTimeout(enhance,0)},true);
    controls.addEventListener('click',function(){setTimeout(function(){refreshControls();enhance()},0)},true);
  }
  document.addEventListener('click',function(){setTimeout(function(){refreshControls();enhance()},0)},true);
  allFonts().then(function(list){return Promise.all(list.map(loadFont))}).catch(function(){}).then(function(){refreshControls();enhance()});
  refreshControls();enhance();
})();