(function(){
'use strict';
var KEY='welog-v2-state',SLOTS='welog-v2-slots',tab='main',zoom=100,images={},stickers=[],editTarget=null;
var defaults={pairName:'PAIR NAME',pairSub:'PAIR CONTENTS',font:'Pretendard',paper:'#ffffff',pairColors:['#efe8dc','#9a958d'],angle:135,centerMode:'split',columns:[310,780,310],left:{name:'Name',sub:'',quote:'한마디를 입력해 주세요.',gender:'-',age:'-',animal:'-',appearance:'이 특징은 기억해주세요.',concept:'',palette:['#302d29','#87827a','#b9b4ac','#f0ede8']},right:{name:'Name',sub:'',quote:'한마디를 입력해 주세요.',gender:'-',age:'-',animal:'-',appearance:'이 특징은 기억해주세요.',concept:'',palette:['#6b5552','#171513','#3f82a6','#f6ece4']},showConcept:'none',showSimplify:true,showColorChange:true,showCredit:true,credit:'커미션 출처를 입력해 주세요.'};
function clone(x){return JSON.parse(JSON.stringify(x))}function merge(a,b){Object.keys(b||{}).forEach(function(k){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k])){a[k]=a[k]||{};merge(a[k],b[k])}else a[k]=b[k]});return a}
var state=merge(clone(defaults),read(KEY,{}));
var legacy=read('welog-pair-sheet-v4',null);
if(!localStorage.getItem(KEY)&&legacy){
 state.pairName=legacy.pairName||state.pairName;state.pairSub=legacy.catchphrase||state.pairSub;state.font=legacy.font||state.font;state.paper=legacy.paper||state.paper;state.centerMode=legacy.centerMode==='combined'?'combined':'split';state.pairColors=legacy.pairColor?[legacy.pairColor.color1,legacy.pairColor.color2]:state.pairColors;state.angle=legacy.pairColor&&legacy.pairColor.angle||state.angle;state.textStyles=legacy.textStyles||{};
 ['left','right'].forEach(function(side){if(!legacy[side])return;['name','quote','gender','age','animal','appearance','concept','palette'].forEach(function(k){if(legacy[side][k]!==undefined)state[side][k]=legacy[side][k]})});
 state.showConcept=legacy.visible&&legacy.visible.concept?(legacy.conceptSide||'left'):'none';state.showSimplify=!!(legacy.right&&legacy.right.outfitOk);state.showColorChange=!!(legacy.right&&legacy.right.colorOk);state.showCredit=!legacy.visible||legacy.visible.commission!==false;state.credit=legacy.commissionCredit||state.credit;
 function importImage(path,src,edit){if(src)images[path]={src:src,scale:edit&&edit.scale?edit.scale/100:1,x:0,y:0,bg:edit&&edit.bg||'#faf8f5'}}
 importImage('left.portrait',legacy.left&&legacy.left.image,legacy.imageEdits&&legacy.imageEdits['left.image']);importImage('right.portrait',legacy.right&&legacy.right.image,legacy.imageEdits&&legacy.imageEdits['right.image']);importImage('center.combined',legacy.pairImage,legacy.imageEdits&&legacy.imageEdits.pairImage);importImage('center.left',legacy.pairImageLeft,legacy.imageEdits&&legacy.imageEdits.pairImageLeft);importImage('center.right',legacy.pairImageRight,legacy.imageEdits&&legacy.imageEdits.pairImageRight);
 stickers=(legacy.stickers||[]).map(function(s){return{src:s.src,x:s.x||50,y:s.y||50,w:s.w||((s.scale||20)*5),r:s.rot||0}});write(KEY,state)
}
function read(k,f){try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch(e){return f}}function write(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function get(path){return path.split('.').reduce(function(o,k){return o&&o[k]},state)}function set(path,v){var p=path.split('.'),o=state;while(p.length>1)o=o[p.shift()];o[p[0]]=v;save()}
var $=function(s,r){return(r||document).querySelector(s)},$$=function(s,r){return[].slice.call((r||document).querySelectorAll(s))};
function lines(text){var a=String(text||'').split(/\n+/).map(function(x){return x.trim()}).filter(Boolean);return a.length?a:['-']}
function image(path,cls){var d=images[path];return'<button class="'+cls+'" data-image="'+path+'" style="background:'+(d&&d.bg||'#faf8f5')+'">'+(d?'<img src="'+d.src+'" style="transform:translate('+(d.x||0)+'px,'+(d.y||0)+'px) scale('+(d.scale||1)+')">':'<span class="image-empty">이미지</span>')+'</button>'}
function profile(side){var d=state[side];return'<section class="profile '+side+'"><div class="profile-name"><h2>'+esc(d.name)+'</h2><p>'+esc(d.sub)+'</p></div>'+image(side+'.portrait','portrait')+'<div class="palette">'+d.palette.map(function(c,i){return'<button data-color="'+side+'.palette.'+i+'" style="background:'+c+'"></button>'}).join('')+'</div><div class="quote">'+esc(d.quote)+'</div><div class="facts"><div class="fact"><span>성별</span><b>'+esc(d.gender||'-')+'</b></div><div class="fact"><span>나이</span><b>'+esc(d.age||'-')+'</b></div><div class="fact"><span>동물화</span><b>'+esc(d.animal||'-')+'</b></div></div><div class="text-section"><h3>외관</h3><ul>'+lines(d.appearance).map(function(x){return'<li>'+esc(x)+'</li>'}).join('')+'</ul></div>'+(state.showConcept===side?'<div class="text-section"><h3>컨셉</h3><ul>'+lines(d.concept).map(function(x){return'<li>'+esc(x)+'</li>'}).join('')+'</ul></div>':'')+(side==='right'?bottomNotes():'')+'</section>'}
function bottomNotes(){return'<div class="bottom-notes">'+(state.showSimplify?'<span>의상 간소화 OK</span>':'')+(state.showColorChange?'<span>색감 변형 OK</span>':'')+(state.showCredit?'<div class="credit"><small>COMMISSION</small><b>'+esc(state.credit)+'</b></div>':'')+'</div>'}
function center(){var paths=state.centerMode==='combined'?['center.combined']:['center.left','center.right'];return'<section class="center-zone"><div class="center-frame"><div class="center-images '+state.centerMode+'">'+paths.map(function(p){return image(p,'center-image')}).join('')+'</div><div class="sticker-layer">'+stickers.map(function(s){return'<img src="'+s.src+'" style="--x:'+s.x+'%;--y:'+s.y+'%;--w:'+s.w+'px;--r:'+s.r+'deg">'}).join('')+'</div></div></section>'}
function renderSheet(){var sh=$('#sheet');sh.style.setProperty('--font',fontStack(state.font));sh.style.setProperty('--paper',state.paper);sh.style.setProperty('--left',state.left.palette[0]);sh.style.setProperty('--right',state.right.palette[0]);sh.style.setProperty('--pair1',state.pairColors[0]);sh.style.setProperty('--pair2',state.pairColors[1]);sh.style.setProperty('--angle',state.angle+'deg');sh.style.setProperty('--col-left',state.columns[0]+'px');sh.style.setProperty('--col-center',state.columns[1]+'px');sh.style.setProperty('--col-right',state.columns[2]+'px');sh.innerHTML='<div class="pair-title"><h1>'+esc(state.pairName)+'</h1><p>'+esc(state.pairSub)+'</p></div><div class="sheet-grid">'+profile('left')+center()+profile('right')+'</div>';bindSheet()}
function bindSheet(){$$('#sheet [data-image]').forEach(function(b){b.onclick=function(){openImage(b.dataset.image)}});$$('#sheet [data-color]').forEach(function(b){b.onclick=function(){openColor(b.dataset.color)}})}
function fontStack(f){return f==='KoPub Batang'?"'KoPub Batang',serif":f==='KoPub Dotum'?"'KoPub Dotum',sans-serif":f==='Noto Sans KR'?"'Noto Sans KR',sans-serif":"Pretendard,'Noto Sans KR',sans-serif"}
function save(){write(KEY,state);var a=$('.autosave');if(a){a.lastChild.textContent='자동 저장 중';clearTimeout(save.t);save.t=setTimeout(function(){a.lastChild.textContent='자동 저장됨'},450)}renderSheet()}
function title(k,t){return'<div class="panel-title"><small>'+k+'</small><h2>'+t+'</h2></div>'}function field(label,path,type){var v=get(path)||'';return'<label class="field"><span>'+label+'</span>'+(type==='textarea'?'<textarea data-path="'+path+'">'+esc(v)+'</textarea>':'<input data-path="'+path+'" value="'+esc(v)+'">')+'</label>'}
function rich(label,path){return field(label,path,'textarea')+'<div class="richbar"><button data-rich="bold" title="굵게"><b>B</b></button><button data-rich="italic" title="기울임"><i>I</i></button><label title="색상">A<input type="color"></label><button title="왼쪽 정렬">←</button><button title="가운데 정렬">↔</button></div>'}
function mainControls(){return title('MAIN','메인')+'<div class="group"><div class="group-title"><b>전체 폰트</b></div><label class="field"><select data-path="font"><option>Pretendard</option><option>Noto Sans KR</option><option>KoPub Batang</option><option>KoPub Dotum</option></select></label></div><div class="group"><div class="group-title"><b>페어 표기</b></div>'+field('페어명','pairName')+field('별도 표기','pairSub')+'</div><div class="group"><div class="group-title"><b>페어 색상</b></div><div class="row"><input type="color" data-path="pairColors.0" value="'+state.pairColors[0]+'"><input type="color" data-path="pairColors.1" value="'+state.pairColors[1]+'"></div><label class="slider"><span>기울기</span><input type="range" min="0" max="360" data-path="angle" value="'+state.angle+'"><b>'+state.angle+'°</b></label></div><div class="group"><div class="group-title"><b>중앙 이미지</b></div><div class="mode"><button data-mode="combined" class="'+(state.centerMode==='combined'?'on':'')+'">합본 (1장)</button><button data-mode="split" class="'+(state.centerMode==='split'?'on':'')+'">분리 (2장)</button></div><div class="image-tools"><button class="tool-card" data-tool="library"><i>▧</i><span><b>이미지 목록</b><small>A · B · 중앙 이미지</small></span></button><button class="tool-card" data-tool="stickers"><i>✦</i><span><b>스티커 편집</b><small>별도 이미지 추가</small></span></button></div></div><div class="group"><div class="group-title"><b>칸 비율</b></div>'+['왼쪽','중앙','오른쪽'].map(function(n,i){return'<label class="slider"><span>'+n+'</span><input type="range" min="220" max="900" data-col="'+i+'" value="'+state.columns[i]+'"><b>'+state.columns[i]+'</b></label>'}).join('')+'</div>'}
function charBlock(side,label){var d=state[side];return'<div class="group"><div class="group-title"><b>'+label+' 캐릭터</b></div>'+field('이름',side+'.name')+field('이름 외 별도 표기',side+'.sub')+'<div class="field"><span>컬러 팔레트</span><div class="colors">'+d.palette.map(function(c,i){return'<input type="color" data-path="'+side+'.palette.'+i+'" value="'+c+'">'}).join('')+'</div></div>'+rich('한마디',side+'.quote')+'<div class="row three">'+field('성별',side+'.gender')+field('나이',side+'.age')+field('동물화',side+'.animal')+'</div>'+rich('외관',side+'.appearance')+rich('컨셉',side+'.concept')+'</div>'}
function characterControls(){return title('CHARACTER','캐릭터')+charBlock('left','A')+charBlock('right','B')}
function checkControls(){return title('CHECK','표시 설정')+'<div class="group"><div class="group-title"><b>컨셉</b></div><div class="mode"><button data-concept="none" class="'+(state.showConcept==='none'?'on':'')+'">표시 안 함</button><button data-concept="left" class="'+(state.showConcept==='left'?'on':'')+'">A만 표시</button><button data-concept="right" class="'+(state.showConcept==='right'?'on':'')+'">B만 표시</button></div></div><div class="group"><div class="group-title"><b>커미션 안내</b></div><div class="check-list"><label><input type="checkbox" data-check="showSimplify" '+(state.showSimplify?'checked':'')+'>의상 간소화 OK</label><label><input type="checkbox" data-check="showColorChange" '+(state.showColorChange?'checked':'')+'>색감 변형 OK</label><label><input type="checkbox" data-check="showCredit" '+(state.showCredit?'checked':'')+'>커미션 출처</label></div>'+field('커미션 출처','credit','textarea')+'</div><button class="danger" id="resetAll">모든 설정 초기화</button>'}
function renderControls(){var c=$('#controls');c.innerHTML=tab==='main'?mainControls():tab==='character'?characterControls():checkControls();bindControls()}
function bindControls(){var c=$('#controls');$$('[data-path]',c).forEach(function(el){if(el.tagName==='SELECT')el.value=get(el.dataset.path);el.oninput=function(){var v=el.type==='range'?+el.value:el.value;set(el.dataset.path,v);var out=el.closest('.slider')&&el.closest('.slider').querySelector('b');if(out)out.textContent=v+(el.dataset.path==='angle'?'°':'')}});$$('[data-mode]',c).forEach(function(b){b.onclick=function(){state.centerMode=b.dataset.mode;save();renderControls()}});$$('[data-concept]',c).forEach(function(b){b.onclick=function(){state.showConcept=b.dataset.concept;save();renderControls()}});$$('[data-check]',c).forEach(function(el){el.onchange=function(){state[el.dataset.check]=el.checked;save()}});$$('[data-col]',c).forEach(function(el){el.oninput=function(){state.columns[+el.dataset.col]=+el.value;var total=state.columns.reduce(function(a,b){return a+b},0),factor=1400/total;state.columns=state.columns.map(function(x){return Math.round(x*factor)});save();var out=el.closest('.slider').querySelector('b');if(out)out.textContent=state.columns[+el.dataset.col]}});$$('[data-tool]',c).forEach(function(b){b.onclick=function(){b.dataset.tool==='library'?openLibrary():openStickers()}});var reset=$('#resetAll');if(reset)reset.onclick=function(){if(confirm('모든 텍스트와 설정을 초기화할까요?')){state=clone(defaults);images={};stickers=[];save();renderControls()}}}
function openColor(path){var input=document.createElement('input');input.type='color';input.value=get(path);input.oninput=function(){set(path,input.value)};input.click()}
function modal(name,body,actions){$('#modalRoot').innerHTML='<div class="modal"><section class="dialog"><header><div><small>WELOG</small><b>'+name+'</b></div><button data-close>×</button></header><div class="dialog-body">'+body+'</div>'+(actions||'')+'</section></div>';$('.modal [data-close]').onclick=closeModal;$('.modal').onclick=function(e){if(e.target.classList.contains('modal'))closeModal()}}
function closeModal(){$('#modalRoot').innerHTML='';editTarget=null}
function openImage(path){editTarget=path;var d=images[path]||{src:'',scale:1,x:0,y:0,bg:'#faf8f5'};modal('이미지 수정','<div class="crop-stage" id="cropStage" style="background:'+d.bg+'">'+(d.src?'<img id="cropImg" src="'+d.src+'" style="--x:'+d.x+'px;--y:'+d.y+'px;--scale:'+d.scale+'">':'<span class="crop-empty">이미지를 선택해 주세요.</span>')+'<i class="crop-outline"></i></div><input id="cropFile" type="file" accept="image/*" hidden><div class="row"><label class="field"><span>배경색</span><input id="cropBg" type="color" value="'+d.bg+'"></label><label class="field"><span>확대</span><input id="cropScale" type="range" min="50" max="300" value="'+Math.round(d.scale*100)+'"></label></div>','<div class="dialog-actions"><button id="cropReset">조정 초기화</button><button id="cropRemove">이미지 삭제</button><button class="primary" id="cropApply">적용</button></div>');var stage=$('#cropStage'),file=$('#cropFile'),draft=clone(d),drag=null;stage.onclick=function(e){if(!draft.src)file.click()};if(draft.src)stage.ondblclick=function(){file.click()};file.onchange=function(){var f=file.files[0];if(!f)return;var rd=new FileReader;rd.onload=function(){draft.src=rd.result;draft.scale=1;draft.x=0;draft.y=0;closeModal();images[path]=draft;openImage(path)};rd.readAsDataURL(f)};stage.onwheel=function(e){if(!draft.src)return;e.preventDefault();draft.scale=Math.max(.5,Math.min(3,draft.scale+(e.deltaY<0?.08:-.08)));$('#cropScale').value=Math.round(draft.scale*100);paint()};stage.onpointerdown=function(e){if(!draft.src)return;drag={x:e.clientX,y:e.clientY,ox:draft.x,oy:draft.y};stage.setPointerCapture(e.pointerId)};stage.onpointermove=function(e){if(!drag)return;draft.x=drag.ox+e.clientX-drag.x;draft.y=drag.oy+e.clientY-drag.y;paint()};stage.onpointerup=function(){drag=null};$('#cropScale').oninput=function(){draft.scale=this.value/100;paint()};$('#cropBg').oninput=function(){draft.bg=this.value;stage.style.background=this.value};$('#cropReset').onclick=function(){draft.scale=1;draft.x=0;draft.y=0;paint()};$('#cropRemove').onclick=function(){delete images[path];closeModal();renderSheet()};$('#cropApply').onclick=function(){images[path]=draft;closeModal();renderSheet()};function paint(){var im=$('#cropImg');if(im)im.style.cssText='--x:'+draft.x+'px;--y:'+draft.y+'px;--scale:'+draft.scale}}
function openLibrary(){var keys=['left.portrait','right.portrait'].concat(state.centerMode==='combined'?['center.combined']:['center.left','center.right']);modal('이미지 목록','<div class="gallery">'+keys.map(function(k){var d=images[k];return'<button data-lib="'+k+'">'+(d?'<img src="'+d.src+'">':'이미지')+'</button>'}).join('')+'</div>');$$('[data-lib]').forEach(function(b){b.onclick=function(){closeModal();openImage(b.dataset.lib)}})}
function openStickers(){modal('스티커 편집','<button class="tool-card" id="stickerUpload"><i>＋</i><span><b>스티커 추가</b></span></button><input id="stickerFile" type="file" accept="image/*" hidden><div class="gallery">'+stickers.map(function(s,i){return'<button data-sticker="'+i+'"><img src="'+s.src+'"></button>'}).join('')+'</div>');$('#stickerUpload').onclick=function(){$('#stickerFile').click()};$('#stickerFile').onchange=function(){var f=this.files[0];if(!f)return;var r=new FileReader;r.onload=function(){stickers.push({src:r.result,x:50,y:82,w:90,r:0});closeModal();renderSheet();openStickers()};r.readAsDataURL(f)};$$('[data-sticker]').forEach(function(b){b.onclick=function(){stickers.splice(+b.dataset.sticker,1);closeModal();renderSheet();openStickers()}})}
function openSlots(){var slots=read(SLOTS,[{name:'슬롯 1'},{name:'슬롯 2'},{name:'슬롯 3'}]);modal('작업 슬롯','<div class="slots-list">'+slots.map(function(s,i){return'<div class="slot-row '+(s.data?'saved':'')+'"><input data-slot-name="'+i+'" value="'+esc(s.name)+'"><button data-slot-save="'+i+'">저장</button><button data-slot-load="'+i+'" '+(s.data?'':'disabled')+'>불러오기</button></div>'}).join('')+'</div>');$$('[data-slot-name]').forEach(function(x){x.onchange=function(){slots[+x.dataset.slotName].name=x.value;write(SLOTS,slots)}});$$('[data-slot-save]').forEach(function(b){b.onclick=function(){var i=+b.dataset.slotSave;slots[i].data=clone(state);write(SLOTS,slots);showToast('슬롯에 저장되었습니다.');closeModal()}});$$('[data-slot-load]').forEach(function(b){b.onclick=function(){var s=slots[+b.dataset.slotLoad];if(s.data){state=merge(clone(defaults),s.data);save();renderControls();closeModal();showToast('슬롯을 불러왔습니다.')}}})}
function showToast(t){var x=$('#toast');x.textContent=t;x.hidden=false;clearTimeout(showToast.t);showToast.t=setTimeout(function(){x.hidden=true},1800)}
async function savePng(){var b=$('#pngBtn'),old=b.textContent;b.disabled=true;b.textContent='저장 중…';try{await document.fonts.ready;var css=window.htmlToImage.getFontEmbedCSS?await window.htmlToImage.getFontEmbedCSS($('#sheet')):'';var url=await window.htmlToImage.toPng($('#sheet'),{width:1400,height:980,canvasWidth:1400,canvasHeight:980,pixelRatio:1,cacheBust:true,skipAutoScale:true,backgroundColor:state.paper,fontEmbedCSS:css,style:{transform:'none',transformOrigin:'top left',margin:'0'}}),a=document.createElement('a');a.download=(state.pairName.trim()||'WeLog')+'.png';a.href=url;a.click()}catch(e){console.error(e);alert('PNG 저장에 실패했습니다.')}finally{b.disabled=false;b.textContent=old}}
function setZoom(v){zoom=Math.max(50,Math.min(150,v));$('#sheetHolder').style.transform='scale('+(zoom/100)+')';$('#zoomText').textContent=zoom+'%';var w=$('.workspace');$('#sheetHolder').style.marginBottom=(980*(zoom/100-1))+'px'}
function boot(){var tabs=$('#tabs');tabs.innerHTML='<button data-tab="main">MAIN</button><button data-tab="character">캐릭터</button><button data-tab="check">체크</button>';$$('[data-tab]').forEach(function(b){b.onclick=function(){tab=b.dataset.tab;$$('[data-tab]').forEach(function(x){x.classList.toggle('on',x===b)});renderControls()}});$('[data-tab="main"]').classList.add('on');$('#slotBtn').onclick=openSlots;$('#pngBtn').onclick=savePng;$('#zoomOut').onclick=function(){setZoom(zoom-10)};$('#zoomIn').onclick=function(){setZoom(zoom+10)};$('#zoomReset').onclick=function(){setZoom(100)};renderSheet();renderControls();setZoom(100);setTimeout(function(){showToast('업데이트 되었습니다.')},400)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
