(function(){
'use strict';
var KEY='welog-v2-state',SLOTS='welog-v2-slots',tab='main',zoom=100,images={},stickers=[],editTarget=null,stickerSelection=-1,imeComposing=false;
var defaults={layout:'basic',photoSlots:6,photoDefaultLeft:'photo.1.left',photoDefaultRight:'photo.1.right',pairName:'PAIR NAME',pairSub:'PAIR CONTENTS',font:'Pretendard',paper:'#ffffff',pairColors:['#efe8dc','#9a958d'],angle:135,centerMode:'split',columns:[310,780,310],left:{name:'Name',sub:'',nameAlign:'left',quote:'한마디를 입력해 주세요.',gender:'-',age:'-',animal:'-',appearance:'이 특징은 기억해주세요.',concept:'',palette:['#302d29','#87827a','#b9b4ac','#f0ede8']},right:{name:'Name',sub:'',nameAlign:'right',quote:'한마디를 입력해 주세요.',gender:'-',age:'-',animal:'-',appearance:'이 특징은 기억해주세요.',concept:'',palette:['#6b5552','#171513','#3f82a6','#f6ece4']},showConcept:'none',showSimplify:true,showColorChange:true,showCredit:true,credit:'커미션 출처를 입력해 주세요.'};
var LAYOUTS={basic:{name:'기본 레이아웃'},photo:{name:'이미지 중심 화보형'}};
function clone(x){return JSON.parse(JSON.stringify(x))}function merge(a,b){Object.keys(b||{}).forEach(function(k){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k])){a[k]=a[k]||{};merge(a[k],b[k])}else a[k]=b[k]});return a}
var state=merge(clone(defaults),read(KEY,{}));
var legacy=read('welog-pair-sheet-v4',null);
if(!localStorage.getItem(KEY)&&legacy){
 state.pairName=legacy.pairName||state.pairName;state.pairSub=legacy.catchphrase||state.pairSub;state.font=legacy.font||state.font;state.paper=legacy.paper||state.paper;state.centerMode=legacy.centerMode==='combined'?'combined':'split';state.pairColors=legacy.pairColor?[legacy.pairColor.color1,legacy.pairColor.color2]:state.pairColors;state.angle=legacy.pairColor&&legacy.pairColor.angle||state.angle;state.textStyles=legacy.textStyles||{};
 ['left','right'].forEach(function(side){if(!legacy[side])return;['name','quote','gender','age','animal','appearance','concept','palette'].forEach(function(k){if(legacy[side][k]!==undefined)state[side][k]=legacy[side][k]})});
 state.showConcept=legacy.visible&&legacy.visible.concept?(legacy.conceptSide||'left'):'none';state.showSimplify=!!(legacy.right&&legacy.right.outfitOk);state.showColorChange=!!(legacy.right&&legacy.right.colorOk);state.showCredit=!legacy.visible||legacy.visible.commission!==false;state.credit=legacy.commissionCredit||state.credit;
 function importImage(path,src,edit){if(src)images[path]={src:src,scale:edit&&edit.scale?edit.scale/100:1,x:0,y:0,bg:edit&&edit.bg||'#faf8f5'}}
 importImage('left.portrait',legacy.left&&legacy.left.image,legacy.imageEdits&&legacy.imageEdits['left.image']);importImage('right.portrait',legacy.right&&legacy.right.image,legacy.imageEdits&&legacy.imageEdits['right.image']);importImage('center.combined',legacy.pairImage,legacy.imageEdits&&legacy.imageEdits.pairImage);importImage('center.left',legacy.pairImageLeft,legacy.imageEdits&&legacy.imageEdits.pairImageLeft);importImage('center.right',legacy.pairImageRight,legacy.imageEdits&&legacy.imageEdits.pairImageRight);
 stickers=(legacy.stickers||[]).map(function(s){return{src:s.src,x:s.x||50,y:s.y||50,w:s.w||((s.scale||20)*5),r:s.rot||0}});write(KEY,state);saveMedia()
}
function read(k,f){try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch(e){return f}}function write(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
function saveMedia(){try{localStorage.setItem('welog-v2-media',JSON.stringify({images:images,stickers:stickers}))}catch(e){}}
function loadMedia(){var m=read('welog-v2-media',null);if(m){images=m.images||images;stickers=m.stickers||stickers}}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function get(path){return path.split('.').reduce(function(o,k){return o&&o[k]},state)}function put(path,v){var p=path.split('.'),o=state;while(p.length>1)o=o[p.shift()];o[p[0]]=v}function set(path,v){put(path,v);save()}
var $=function(s,r){return(r||document).querySelector(s)},$$=function(s,r){return[].slice.call((r||document).querySelectorAll(s))};
function lines(text){var a=String(text||'').split(/\n+/).map(function(x){return x.trim()}).filter(Boolean);return a.length?a:['-']}
function image(path,cls){var d=images[path],x=d&&(d.x||0),y=d&&(d.y||0),isLeft=path===state.photoDefaultLeft,isRight=path===state.photoDefaultRight,badge=state.layout==='photo'&&(isLeft||isRight)?'<span class="default-outfit-badge">★ '+(isLeft?'A':'B')+' 기본 의상</span>':'';if(d&&d.unit!=='percent'){x=x/5.64;y=y/3.34}return'<button class="'+cls+'" data-image="'+path+'" style="background:'+(d&&d.bg||'#faf8f5')+'">'+(d?'<img src="'+d.src+'" style="left:calc(50% + '+x+'%);top:calc(50% + '+y+'%);transform:translate(-50%,-50%) scale('+(d.scale||1)+')">':'<span class="image-empty">이미지</span>')+badge+'</button>'}
function profile(side){var d=state[side],align=d.nameAlign||(side==='right'?'right':'left');return'<section class="profile '+side+'"><div class="profile-name" style="text-align:'+align+'"><h2>'+esc(d.name)+'</h2><p>'+esc(d.sub)+'</p></div>'+image(side+'.portrait','portrait')+'<div class="palette">'+d.palette.map(function(c,i){return'<button data-color="'+side+'.palette.'+i+'" style="background:'+c+'"></button>'}).join('')+'</div><div class="quote">'+esc(d.quote)+'</div><div class="facts"><div class="fact"><span>성별</span><b>'+esc(d.gender||'-')+'</b></div><div class="fact"><span>나이</span><b>'+esc(d.age||'-')+'</b></div><div class="fact"><span>동물화</span><b>'+esc(d.animal||'-')+'</b></div></div><div class="text-section"><h3>외관</h3><ul>'+lines(d.appearance).map(function(x){return'<li>'+esc(x)+'</li>'}).join('')+'</ul></div>'+((state.showConcept===side||state.showConcept==='both')?'<div class="text-section"><h3>컨셉</h3><ul>'+lines(d.concept).map(function(x){return'<li>'+esc(x)+'</li>'}).join('')+'</ul></div>':'')+'</section>'}
function bottomNotes(){return'<div class="bottom-notes">'+(state.showSimplify?'<span>의상 간소화 OK</span>':'')+(state.showColorChange?'<span>색감 변형 OK</span>':'')+(state.showCredit?'<div class="credit"><small>COMMISSION</small><b>'+esc(state.credit)+'</b></div>':'')+'</div>'}
function center(){var paths=state.centerMode==='combined'?['center.combined']:['center.left','center.right'];return'<section class="center-zone"><div class="center-frame"><div class="center-images '+state.centerMode+'">'+paths.map(function(p){return image(p,'center-image')}).join('')+'</div></div></section>'}
function photoLayout(){var count=+state.photoSlots||6,rows=Array.from({length:count/2},function(_,i){return i+1});return'<div class="pair-title photo-title"><h1>'+esc(state.pairName)+'</h1><p>'+esc(state.pairSub)+'</p></div><div class="sheet-grid photo-sheet-grid">'+profile('left')+'<section class="photo-center"><div class="photo-board slots-'+count+'">'+rows.map(function(n){return'<div class="photo-strip">'+image('photo.'+n+'.left','photo-slot')+image('photo.'+n+'.right','photo-slot')+'</div>'}).join('')+'</div></section>'+profile('right')+'</div>'}
function stickerLayer(){return'<div class="sticker-layer">'+stickers.map(function(s,i){return'<div data-sticker-sheet="'+i+'" class="sticker-item '+(i===stickerSelection?'selected ':'')+(s.locked?'locked':'')+'" style="--x:'+s.x+'%;--y:'+s.y+'%;--w:'+s.w+'px;--r:'+s.r+'deg"><img src="'+s.src+'"><div class="sticker-transform-ui"><button class="sticker-canvas-lock" data-sticker-canvas-lock title="'+(s.locked?'잠금 해제':'잠금')+'">'+(s.locked?'🔒':'🔓')+'</button><button class="sticker-canvas-delete" data-sticker-canvas-delete title="삭제">×</button><i class="sticker-rotate" title="회전"></i><i class="sticker-resize" title="크기"></i></div></div>'}).join('')+'</div>'}
function layoutMarkup(){var key=LAYOUTS[state.layout]?state.layout:'basic',body=key==='photo'?photoLayout():'<div class="pair-title"><h1>'+esc(state.pairName)+'</h1><p>'+esc(state.pairSub)+'</p></div><div class="sheet-grid">'+profile('left')+center()+profile('right')+'</div>';return'<div class="layout-canvas layout-'+key+'">'+body+'</div>'+stickerLayer()+bottomNotes()}
function renderSheet(){var sh=$('#sheet'),layout=LAYOUTS[state.layout]?state.layout:'basic';sh.dataset.layout=layout;sh.style.setProperty('--font',fontStack(state.font));sh.style.setProperty('--paper',state.paper);sh.style.setProperty('--left',state.left.palette[0]);sh.style.setProperty('--right',state.right.palette[0]);sh.style.setProperty('--pair1',state.pairColors[0]);sh.style.setProperty('--pair2',state.pairColors[1]);sh.style.setProperty('--angle',state.angle+'deg');sh.style.setProperty('--col-left',state.columns[0]+'px');sh.style.setProperty('--col-center',state.columns[1]+'px');sh.style.setProperty('--col-right',state.columns[2]+'px');sh.innerHTML=layoutMarkup();bindSheet()}
function bindSheet(){$$('#sheet [data-image]').forEach(function(b){b.onclick=function(){openImage(b.dataset.image)}});$$('#sheet [data-color]').forEach(function(b){b.onclick=function(){openColor(b.dataset.color)}});$$('#sheet [data-sticker-sheet]').forEach(function(item){var i=+item.dataset.stickerSheet,s=stickers[i],drag=null,resize=null,rotate=null;function refreshPanel(){saveMedia();if(tab==='main')renderControls()}item.onclick=function(e){e.stopPropagation();if(stickerSelection!==i){stickerSelection=i;renderSheet();if(tab==='main')renderControls()}};item.onwheel=function(e){if(s.locked)return;e.preventDefault();e.stopPropagation();stickerSelection=i;s.w=Math.max(30,Math.min(320,s.w+(e.deltaY<0?8:-8)));saveMedia();renderSheet();if(tab==='main')renderControls()};item.onpointerdown=function(e){if(e.target.closest('.sticker-transform-ui')||s.locked)return;e.preventDefault();e.stopPropagation();stickerSelection=i;var frame=item.closest('.sheet').getBoundingClientRect();drag={x:e.clientX,y:e.clientY,ox:s.x,oy:s.y,frame:frame};item.classList.add('selected');item.setPointerCapture(e.pointerId)};item.onpointermove=function(e){if(drag){s.x=Math.max(0,Math.min(100,drag.ox+(e.clientX-drag.x)/drag.frame.width*100));s.y=Math.max(0,Math.min(100,drag.oy+(e.clientY-drag.y)/drag.frame.height*100));item.style.setProperty('--x',s.x+'%');item.style.setProperty('--y',s.y+'%')}else if(resize){s.w=Math.max(30,Math.min(320,resize.ow+(e.clientX-resize.x)/resize.frame.width*1400));item.style.setProperty('--w',s.w+'px')}else if(rotate){s.r=Math.atan2(e.clientY-rotate.cy,e.clientX-rotate.cx)*180/Math.PI+90;item.style.setProperty('--r',s.r+'deg')}};item.onpointerup=function(){if(!drag&&!resize&&!rotate)return;drag=resize=rotate=null;refreshPanel()};var rh=item.querySelector('.sticker-resize');rh.onpointerdown=function(e){if(s.locked)return;e.preventDefault();e.stopPropagation();stickerSelection=i;resize={x:e.clientX,ow:s.w,frame:item.closest('.sheet').getBoundingClientRect()};item.setPointerCapture(e.pointerId)};var ro=item.querySelector('.sticker-rotate');ro.onpointerdown=function(e){if(s.locked)return;e.preventDefault();e.stopPropagation();stickerSelection=i;var box=item.getBoundingClientRect();rotate={cx:box.left+box.width/2,cy:box.top+box.height/2};item.setPointerCapture(e.pointerId)};item.querySelector('[data-sticker-canvas-lock]').onclick=function(e){e.stopPropagation();s.locked=!s.locked;refreshPanel();renderSheet()};item.querySelector('[data-sticker-canvas-delete]').onclick=function(e){e.stopPropagation();stickers.splice(i,1);stickerSelection=Math.min(i,stickers.length-1);refreshPanel();renderSheet()}})}
function fontStack(f){return f==='KoPub Batang'?"'KoPub Batang',serif":f==='KoPub Dotum'?"'KoPub Dotum',sans-serif":f==='Noto Sans KR'?"'Noto Sans KR',sans-serif":"Pretendard,'Noto Sans KR',sans-serif"}
function queueSheetRender(){clearTimeout(queueSheetRender.t);if(imeComposing)return;queueSheetRender.t=setTimeout(function(){if(!imeComposing)renderSheet()},120)}
function save(){write(KEY,state);var a=$('.autosave');if(a){a.lastChild.textContent='자동 저장 중';clearTimeout(save.t);save.t=setTimeout(function(){a.lastChild.textContent='자동 저장됨'},450)}queueSheetRender()}
function title(k,t){return'<div class="panel-title"><small>'+k+'</small><h2>'+t+'</h2></div>'}function field(label,path,type){var v=get(path)||'';return'<label class="field"><span>'+label+'</span>'+(type==='textarea'?'<textarea data-path="'+path+'">'+esc(v)+'</textarea>':'<input data-path="'+path+'" value="'+esc(v)+'">')+'</label>'}
function rich(label,path){return field(label,path,'textarea')+'<div class="richbar"><button data-rich="bold" title="굵게"><b>B</b></button><button data-rich="italic" title="기울임"><i>I</i></button><label title="색상">A<input type="color"></label><button title="왼쪽 정렬">←</button><button title="가운데 정렬">↔</button></div>'}
function mainImageKeys(){if(state.layout==='photo')return Array.from({length:(+state.photoSlots||6)/2},function(_,i){return i+1}).reduce(function(a,n){return a.concat([{path:'photo.'+n+'.left',name:n+'번째 A 의상'},{path:'photo.'+n+'.right',name:n+'번째 B 의상'}])},[]);var a=[{path:'left.portrait',name:'A 두상'},{path:'right.portrait',name:'B 두상'}];return a.concat(state.centerMode==='combined'?[{path:'center.combined',name:'중앙 이미지'}]:[{path:'center.left',name:'A 전신'},{path:'center.right',name:'B 전신'}])}
function stickerPanel(){return'<div class="main-media-section sticker-section"><div class="subsection-title"><b>스티커 편집</b><small>선택 후 시트에서 바로 편집</small></div><button class="sticker-inline-add" data-sticker-add>＋ 스티커 추가</button><div class="sticker-inline-list">'+(stickers.length?stickers.map(function(x,i){return'<button class="'+(i===stickerSelection?'on':'')+'" data-sticker-pick="'+i+'"><img src="'+x.src+'"><span>스티커 '+(i+1)+'</span><i>'+(x.locked?'●':'○')+'</i></button>'}).join(''):'<p>등록된 스티커가 없습니다.</p>')+'</div></div>'}
function layoutPicker(){return'<div class="group layout-picker"><div class="group-title"><b>레이아웃</b><small>시트 구성을 선택하세요</small></div><label class="field"><select data-path="layout"><option value="basic">기본 레이아웃</option><option value="photo">이미지 중심 화보형</option></select></label></div>'}
function photoSlotPicker(){return'<div class="group photo-slot-picker"><div class="group-title"><b>의상 이미지 칸</b><small>사용할 이미지 개수를 선택하세요</small></div><div class="mode"><button data-photo-slots="2" class="'+(+state.photoSlots===2?'on':'')+'">2칸</button><button data-photo-slots="4" class="'+(+state.photoSlots===4?'on':'')+'">4칸</button><button data-photo-slots="6" class="'+(+state.photoSlots===6?'on':'')+'">6칸</button></div></div>'}
function photoDefaultPicker(){var keys=mainImageKeys();function options(side){return keys.filter(function(k){return k.path.endsWith('.'+side)}).map(function(k){return'<option value="'+k.path+'">'+k.name+'</option>'}).join('')}return'<div class="group default-outfit-picker"><div class="group-title"><b>기본 의상</b><small>각 캐릭터의 대표 의상을 선택하세요</small></div><label class="field"><span>A 캐릭터</span><select data-path="photoDefaultLeft">'+options('left')+'</select></label><label class="field"><span>B 캐릭터</span><select data-path="photoDefaultRight">'+options('right')+'</select></label></div>'}
function mainControls(){return title('MAIN','메인')+'<div class="group"><div class="group-title"><b>전체 폰트</b></div><label class="field"><select data-path="font"><option>Pretendard</option><option>Noto Sans KR</option><option>KoPub Batang</option><option>KoPub Dotum</option></select></label></div><div class="group"><div class="group-title"><b>페어 표기</b></div>'+field('페어명','pairName')+field('별도 표기','pairSub')+'</div><div class="group"><div class="group-title"><b>페어 색상</b></div><div class="row"><input type="color" data-path="pairColors.0" value="'+state.pairColors[0]+'"><input type="color" data-path="pairColors.1" value="'+state.pairColors[1]+'"></div><label class="slider"><span>기울기</span><input type="range" min="0" max="360" data-path="angle" value="'+state.angle+'"><b>'+state.angle+'°</b></label></div><div class="group"><div class="group-title"><b>이미지 목록</b></div><div class="mode"><button data-mode="combined" class="'+(state.centerMode==='combined'?'on':'')+'">합본 (1장)</button><button data-mode="split" class="'+(state.centerMode==='split'?'on':'')+'">분리 (2장)</button></div><div class="main-media-section"><div class="subsection-title"><b>LIST</b><small>클릭해서 삽입·수정</small></div><div class="inline-gallery">'+mainImageKeys().map(function(k){var d=images[k.path];return'<button data-main-image="'+k.path+'">'+(d&&d.src?'<img src="'+d.src+'">':'<i>＋</i>')+'<span>'+k.name+'</span></button>'}).join('')+'</div></div>'+stickerPanel()+'</div><div class="group"><div class="group-title"><b>칸 비율</b></div>'+['왼쪽','중앙','오른쪽'].map(function(n,i){return'<label class="slider"><span>'+n+'</span><input type="range" min="220" max="900" data-col="'+i+'" value="'+state.columns[i]+'"><b>'+state.columns[i]+'</b></label>'}).join('')+'</div>'}
function charBlock(side,label){var d=state[side],on=state.showConcept===side||state.showConcept==='both';return'<div class="group character-group"><div class="group-title"><b>'+label+' 캐릭터</b></div>'+field('이름',side+'.name')+field('이름 외 별도 표기',side+'.sub')+'<label class="field"><span>이름 · 별도 표기 정렬</span><select data-path="'+side+'.nameAlign"><option value="left">왼쪽</option><option value="center">가운데</option><option value="right">오른쪽</option></select></label><div class="field"><span>컬러 팔레트</span><div class="colors">'+d.palette.map(function(c,i){return'<input type="color" data-path="'+side+'.palette.'+i+'" value="'+c+'">'}).join('')+'</div></div>'+rich('한마디',side+'.quote')+'<div class="row three facts-control">'+field('성별',side+'.gender')+field('나이',side+'.age')+field('동물화',side+'.animal')+'</div>'+rich('외관',side+'.appearance')+'<div class="concept-control"><div class="group-title"><b>컨셉</b><label><input type="checkbox" data-concept-toggle="'+side+'" '+(on?'checked':'')+'> 시트에 표시</label></div>'+rich('컨셉 내용',side+'.concept')+'</div></div>'}
function characterControls(){return title('CHARACTER','캐릭터')+charBlock('left','A')+charBlock('right','B')}
function checkControls(){return title('CHECK','표시 설정')+'<div class="group"><div class="group-title"><b>커미션 안내</b></div><div class="check-list"><label><input type="checkbox" data-check="showSimplify" '+(state.showSimplify?'checked':'')+'>의상 간소화 OK</label><label><input type="checkbox" data-check="showColorChange" '+(state.showColorChange?'checked':'')+'>색감 변형 OK</label><label><input type="checkbox" data-check="showCredit" '+(state.showCredit?'checked':'')+'>커미션 출처</label></div>'+field('커미션 출처','credit','textarea')+'</div><button class="danger" id="resetAll">모든 설정 초기화</button>'}
function renderControls(){var c=$('#controls');c.dataset.layout=state.layout||'basic';c.innerHTML=tab==='main'?mainControls():tab==='character'?characterControls():checkControls();if(tab==='main')c.insertAdjacentHTML('afterbegin',layoutPicker()+(state.layout==='photo'?photoSlotPicker()+photoDefaultPicker():''));bindControls();$$('[data-photo-slots]',c).forEach(function(b){b.onclick=function(){state.photoSlots=+b.dataset.photoSlots;var keys=mainImageKeys().map(function(k){return k.path});if(keys.indexOf(state.photoDefaultLeft)<0)state.photoDefaultLeft='photo.1.left';if(keys.indexOf(state.photoDefaultRight)<0)state.photoDefaultRight='photo.1.right';write(KEY,state);renderSheet();renderControls()}});$$('[data-path="photoDefaultLeft"],[data-path="photoDefaultRight"]',c).forEach(function(outfit){outfit.onchange=function(){state[outfit.dataset.path]=outfit.value;write(KEY,state);renderSheet();renderControls()}});var picker=c.querySelector('[data-path="layout"]');if(picker){var before=state.layout;picker.onchange=function(){if(before===picker.value)return;images={};stickers=[];stickerSelection=-1;state.layout=picker.value;write(KEY,state);saveMedia();renderSheet();renderControls();showToast('새 레이아웃에서 이미지를 다시 등록해 주세요.')}}}
function bindControls(){var c=$('#controls');$$('[data-path]',c).forEach(function(el){if(el.tagName==='SELECT')el.value=get(el.dataset.path);el.oninput=function(){var v=el.type==='range'?+el.value:el.value;set(el.dataset.path,v);var out=el.closest('.slider')&&el.closest('.slider').querySelector('b');if(out)out.textContent=v+(el.dataset.path==='angle'?'°':'')}});$$('[data-mode]',c).forEach(function(b){b.onclick=function(){state.centerMode=b.dataset.mode;save();renderControls()}});[].forEach.call(c.querySelectorAll('[data-concept-toggle]'),function(el){el.onchange=function(){var left=c.querySelector('[data-concept-toggle="left"]'),right=c.querySelector('[data-concept-toggle="right"]');state.showConcept=left&&left.checked&&right&&right.checked?'both':left&&left.checked?'left':right&&right.checked?'right':'none';write(KEY,state);renderSheet();var a=$('.autosave');if(a)a.lastChild.textContent='자동 저장됨'}});$$('[data-main-image]',c).forEach(function(b){b.onclick=function(){openImage(b.dataset.mainImage)}});[].forEach.call(c.querySelectorAll('[data-sticker-add]'),function(b){b.onclick=addStickerInline});[].forEach.call(c.querySelectorAll('[data-sticker-pick]'),function(b){b.onclick=function(){stickerSelection=+b.dataset.stickerPick;renderSheet();renderControls()}});[].forEach.call(c.querySelectorAll('[data-sticker-lock]'),function(b){b.onclick=function(){var s=stickers[+b.dataset.stickerLock];s.locked=!s.locked;saveMedia();renderSheet();renderControls()}});[].forEach.call(c.querySelectorAll('[data-sticker-delete]'),function(b){b.onclick=function(){stickers.splice(+b.dataset.stickerDelete,1);stickerSelection=Math.min(stickerSelection,stickers.length-1);saveMedia();renderSheet();renderControls()}});[].forEach.call(c.querySelectorAll('[data-sticker-inline-prop]'),function(x){x.oninput=function(){var s=stickers[stickerSelection],v=+x.value;s[x.dataset.stickerInlineProp]=v;x.parentNode.querySelector('em').textContent=v+(x.dataset.stickerInlineProp==='x'||x.dataset.stickerInlineProp==='y'?'%':x.dataset.stickerInlineProp==='r'?'°':'');saveMedia();renderSheet()}});[].forEach.call(c.querySelectorAll('[data-check]'),function(el){el.onchange=function(){state[el.dataset.check]=el.checked;save()}});$$('[data-col]',c).forEach(function(el){el.oninput=function(){state.columns[+el.dataset.col]=+el.value;var total=state.columns.reduce(function(a,b){return a+b},0),factor=1400/total;state.columns=state.columns.map(function(x){return Math.round(x*factor)});save();var out=el.closest('.slider').querySelector('b');if(out)out.textContent=state.columns[+el.dataset.col]}});$$('[data-tool]',c).forEach(function(b){b.onclick=function(){b.dataset.tool==='library'?openLibrary():openStickers()}});var reset=$('#resetAll');if(reset)reset.onclick=function(){if(confirm('모든 텍스트와 설정을 초기화할까요?')){state=clone(defaults);images={};stickers=[];save();renderControls()}}}
function openColor(path){var input=document.createElement('input');input.type='color';input.value=get(path);input.oninput=function(){set(path,input.value)};input.click()}
function modal(name,body,actions){$('#modalRoot').innerHTML='<div class="modal"><section class="dialog"><header><div><small>WELOG</small><b>'+name+'</b></div><button data-close>×</button></header><div class="dialog-body">'+body+'</div>'+(actions||'')+'</section></div>';$('.modal [data-close]').onclick=closeModal;$('.modal').onclick=function(e){if(e.target.classList.contains('modal'))closeModal()}}
function closeModal(){$('#modalRoot').innerHTML='';editTarget=null}
function openImage(path){
 editTarget=path;var source=images[path]||{src:'',scale:1,x:0,y:0,bg:'#faf8f5',unit:'percent'},d=clone(source);
 if(d.unit!=='percent'){d.x=(d.x||0)/5.64;d.y=(d.y||0)/3.34;d.unit='percent'}
 var target=$('#sheet [data-image="'+path+'"]'),tw=target?target.offsetWidth:520,th=target?target.offsetHeight:390,ratio=tw/th,vw=564,vh=Math.round(564/ratio);if(vh>350){vh=350;vw=Math.round(350*ratio)}
 modal('이미지 수정','<div class="crop-stage" id="cropStage" style="background:'+d.bg+'"><div class="crop-viewport" id="cropViewport" style="width:'+vw+'px;height:'+vh+'px;background:'+d.bg+'">'+(d.src?'<img id="cropImg" src="'+d.src+'">':'<span class="crop-empty">이미지를 선택해 주세요.</span>')+'</div></div><input id="cropFile" type="file" accept="image/*" hidden><div class="row"><label class="field"><span>배경색</span><input id="cropBg" type="color" value="'+d.bg+'"></label><label class="field"><span>확대</span><input id="cropScale" type="range" min="50" max="300" value="'+Math.round(d.scale*100)+'"></label></div>','<div class="dialog-actions"><button id="cropReset">조정 초기화</button><button id="cropRemove">이미지 삭제</button><button class="primary" id="cropApply">적용</button></div>');
 var stage=$('#cropStage'),viewport=$('#cropViewport'),file=$('#cropFile'),draft=d,drag=null,raf=0;
 stage.onclick=function(){if(!draft.src)file.click()};if(draft.src)stage.ondblclick=function(){file.click()};file.onchange=function(){var f=file.files[0];if(!f)return;var rd=new FileReader;rd.onload=function(){draft.src=rd.result;draft.scale=1;draft.x=0;draft.y=0;draft.unit='percent';closeModal();images[path]=draft;openImage(path)};rd.readAsDataURL(f)};
 stage.onwheel=function(e){if(!draft.src)return;e.preventDefault();draft.scale=Math.max(.5,Math.min(3,draft.scale+(e.deltaY<0?.08:-.08)));$('#cropScale').value=Math.round(draft.scale*100);paint()};viewport.onpointerdown=function(e){if(!draft.src)return;e.preventDefault();drag={x:e.clientX,y:e.clientY,ox:draft.x||0,oy:draft.y||0};viewport.setPointerCapture(e.pointerId)};viewport.onpointermove=function(e){if(!drag)return;draft.x=drag.ox+(e.clientX-drag.x)/viewport.clientWidth*100;draft.y=drag.oy+(e.clientY-drag.y)/viewport.clientHeight*100;paint()};viewport.onpointerup=function(){drag=null};
 $('#cropScale').oninput=function(){draft.scale=this.value/100;paint()};$('#cropBg').oninput=function(){draft.bg=this.value;stage.style.background=this.value;viewport.style.background=this.value};$('#cropReset').onclick=function(){draft.scale=1;draft.x=0;draft.y=0;paint()};$('#cropRemove').onclick=function(){delete images[path];saveMedia();closeModal();renderSheet();if(tab==='main')renderControls()};$('#cropApply').onclick=function(){draft.unit='percent';images[path]=draft;saveMedia();closeModal();renderSheet();if(tab==='main')renderControls()};
 function paint(){if(raf)return;raf=requestAnimationFrame(function(){raf=0;var im=$('#cropImg');if(im){im.style.left='calc(50% + '+(draft.x||0)+'%)';im.style.top='calc(50% + '+(draft.y||0)+'%)';im.style.transform='translate(-50%,-50%) scale('+(draft.scale||1)+')'}})}paint()
}
function openLibrary(){var keys=['left.portrait','right.portrait'].concat(state.centerMode==='combined'?['center.combined']:['center.left','center.right']);modal('이미지 목록','<div class="gallery">'+keys.map(function(k){var d=images[k];return'<button data-lib="'+k+'">'+(d?'<img src="'+d.src+'">':'이미지')+'</button>'}).join('')+'</div>');$$('[data-lib]').forEach(function(b){b.onclick=function(){closeModal();openImage(b.dataset.lib)}})}
function addStickerInline(){var file=document.createElement('input');file.type='file';file.accept='image/*';file.hidden=true;document.body.appendChild(file);file.onchange=function(){var f=this.files[0];if(!f){file.remove();return}var rd=new FileReader;rd.onload=function(){stickers.push({src:rd.result,x:50,y:82,w:90,r:0,locked:false});stickerSelection=stickers.length-1;file.remove();saveMedia();renderSheet();if(tab==='main')renderControls()};rd.readAsDataURL(f)};file.click()}
function openStickers(){addStickerInline()}
function openSlots(){var slots=read(SLOTS,[]);while(slots.length<5)slots.push({name:'슬롯 '+(slots.length+1)});slots=slots.slice(0,5);write(SLOTS,slots);modal('작업 슬롯','<p class="slots-help">저장된 작업을 불러오거나 빈 슬롯에서 새로 시작하세요.</p><div class="slots-list">'+slots.map(function(s,i){return'<div class="slot-row '+(s.data?'saved':'empty')+'"><span class="slot-number">'+String(i+1).padStart(2,'0')+'</span><input data-slot-name="'+i+'" value="'+esc(s.name)+'" placeholder="슬롯 이름을 입력하세요"><i class="slot-status" title="'+(s.data?'저장됨':'비어 있음')+'"></i><button data-slot-save="'+i+'">저장</button><button class="load" data-slot-load="'+i+'">'+(s.data?'불러오기':'새로 시작')+'</button></div>'}).join('')+'</div>');$('.dialog').classList.add('slots-dialog');$$('[data-slot-name]').forEach(function(x){x.onchange=function(){slots[+x.dataset.slotName].name=x.value||('슬롯 '+(+x.dataset.slotName+1));write(SLOTS,slots)}});$$('[data-slot-save]').forEach(function(b){b.onclick=function(){var i=+b.dataset.slotSave;slots[i].name=$('[data-slot-name="'+i+'"]').value||('슬롯 '+(i+1));slots[i].data=clone(state);write(SLOTS,slots);showToast('슬롯에 저장되었습니다.');openSlots()}});$$('[data-slot-load]').forEach(function(b){b.onclick=function(){var i=+b.dataset.slotLoad,s=slots[i];if(s.data){state=merge(clone(defaults),s.data);save();renderControls();closeModal();showToast('슬롯을 불러왔습니다.')}else{state=clone(defaults);images={};stickers=[];stickerSelection=-1;write(KEY,state);saveMedia();renderSheet();renderControls();closeModal();showToast((s.name||('슬롯 '+(i+1)))+'에서 새로 시작합니다.')}}})}
function showToast(t){var x=$('#toast');x.textContent=t;x.hidden=false;clearTimeout(showToast.t);showToast.t=setTimeout(function(){x.hidden=true},1800)}
function openPreview(){modal('미리보기','<div class="preview-frame"><div id="previewMount"></div></div>');var dialog=$('.dialog'),mount=$('#previewMount'),copy=$('#sheet').cloneNode(true),scale=Math.min((window.innerWidth-150)/1400,(window.innerHeight-190)/1020,.82);dialog.classList.add('preview-dialog');copy.removeAttribute('id');copy.style.transform='scale('+scale+')';copy.style.transformOrigin='top left';mount.style.width=Math.round(1400*scale)+'px';mount.style.height=Math.round(1020*scale)+'px';mount.appendChild(copy)}
async function savePng(){var b=$('#pngBtn'),old=b.textContent,sh=$('#sheet');sh.classList.add('exporting');b.disabled=true;b.textContent='저장 중…';try{await document.fonts.ready;var css=window.htmlToImage.getFontEmbedCSS?await window.htmlToImage.getFontEmbedCSS($('#sheet')):'';var url=await window.htmlToImage.toPng($('#sheet'),{width:1400,height:1020,canvasWidth:1400,canvasHeight:1020,pixelRatio:1,cacheBust:true,skipAutoScale:true,backgroundColor:state.paper,fontEmbedCSS:css,style:{transform:'none',transformOrigin:'top left',margin:'0'}}),a=document.createElement('a');a.download=(state.pairName.trim()||'WeLog')+'.png';a.href=url;a.click()}catch(e){console.error(e);alert('PNG 저장에 실패했습니다.')}finally{sh.classList.remove('exporting');b.disabled=false;b.textContent=old}}
function setZoom(v){zoom=Math.max(50,Math.min(150,v));var work=$('.workspace'),pad=24,fit=Math.min((work.clientWidth-pad)/1400,(work.clientHeight-pad)/1020,1),scale=Math.max(.2,fit)*(zoom/100),holder=$('#sheetHolder'),sheet=$('#sheet');holder.style.width=Math.round(1400*scale)+'px';holder.style.height=Math.round(1020*scale)+'px';holder.style.transform='none';holder.style.margin='0 auto';sheet.style.transformOrigin='top left';sheet.style.transform='scale('+scale+')';$('#zoomText').textContent=zoom+'%'}
function boot(){loadMedia();document.addEventListener('compositionstart',function(){imeComposing=true;clearTimeout(queueSheetRender.t)},true);document.addEventListener('compositionend',function(){imeComposing=false;queueSheetRender()},true);document.addEventListener('click',function(e){var target=e.target,closest=target&&target.closest?target.closest.bind(target):function(){return null};if(closest('#cropApply,#cropRemove,[data-sticker]'))setTimeout(saveMedia,0);if(stickerSelection>=0&&!closest('[data-sticker-sheet],[data-sticker-pick],[data-sticker-add]')){stickerSelection=-1;renderSheet();$$('[data-sticker-pick].on').forEach(function(b){b.classList.remove('on')})}});document.addEventListener('change',function(e){if(e.target.id==='stickerFile')setTimeout(saveMedia,120)});var tabs=$('#tabs');tabs.innerHTML='<button data-tab="main">메인</button><button data-tab="character">캐릭터</button><button data-tab="check">체크</button>';$$('[data-tab]').forEach(function(b){b.onclick=function(){tab=b.dataset.tab;$$('[data-tab]').forEach(function(x){x.classList.toggle('on',x===b)});renderControls()}});$('[data-tab="main"]').classList.add('on');$('#slotBtn').onclick=openSlots;$('#previewBtn').onclick=openPreview;$('#pngBtn').onclick=savePng;$('#zoomOut').onclick=function(){setZoom(zoom-10)};$('#zoomIn').onclick=function(){setZoom(zoom+10)};$('#zoomReset').onclick=function(){setZoom(100)};window.addEventListener('resize',function(){setZoom(zoom)});renderSheet();renderControls();requestAnimationFrame(function(){setZoom(100)});setTimeout(function(){showToast('업데이트 되었습니다.')},400)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
